/*
    POLARION
    Code written by non-profit organization "POLARION" (SIREN 930088620)
    @Copyright POLARION (https://www.polarion.fr)
    YOU ARE NOT ALLOWED TO COPY OR DISTRIBUTE THE CONTENT OF THIS FILE WITHOUT AUTHOR AGREEMENT
    More informations : https://www.bistudio.com/community/game-content-usage-rules
    Contact : hello@polarion.fr
*/
// Useable Name, Display Name, Weight, Class Name, dir, canDrop, canGive, canUse, canPickup, simulation, fnc, attach, desc, maxTake, picture
// Config_ItemMap = createHashMapFromArray
// [
// 	["acetone",["Acétone",0.1,"A3FL_Acetone",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["acrylic",["Acrylique",0.2,"A3PL_Acrylic",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["aluminium",["Aluminium",1,"A3PL_Aluminium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sheet.paa"]],
// 	["aluminium_ingot",["Lingot d'aluminium",0.2,"A3PL_Ingot_Aluminium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["aluminium_ingot_pellet",["Palette de lingots d'aluminium",15,"A3PL_Ingot_Pallet_Aluminium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["aluminium_ore",["Minerai de bauxite",0.25,"A3PL_Resource_Ore_Bauxite_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["aluminium_pellet",["Palette d'aluminium",15,"A3PL_Pallet_Aluminium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["amethyst_ingot",["Lingot d'améthyste",0.2,"A3PL_Ingot_Amethyst",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["amethyst_ingot_pallet",["Palette de lingots d'améthyste",15,"A3PL_Ingot_Pallet_Amethyst",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["amethyst_ore",["Minerai d'améthyste",0.25,"A3PL_Resource_Ore_Amethyst_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["ammonium_hydroxide",["Hydroxyde d'ammonium",0.1,"A3FL_Ammonium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["apple",["Pomme",1,"A3PL_Apple",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\apple.paa"]],
// 	["applecookies",["Biscuit à la pomme",0.1,"A3PL_Timtams",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\biscuit.paa"]],
// 	["applejuice",["Jus de pomme",0.1,"A3FL_AppleJuice",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\applejuice.paa"]],
// 	["carrotjuice",["Jus de carotte",0.1,"A3FL_AppleJuice",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\carrotjuice.paa"]],
// 	["aramid",["Aramide",1,"A3PL_Aramid",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\box.paa"]],
// 	["bakingsoda",["Bicarbonate de soude",1,"A3FL_BakingSoda",1,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\bakingsoda.paa"]],
// 	["banana",["Banane",0.5,"A3FL_Banana",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\banana.paa"]],
// 	["beer",["Bière Corona",0.1,"A3PL_Corona",20,true,true,true,true,true,"A3PL_Items_Thirst",[-0.03,-0.05,0.1],"",5,"po_ui\Data\items\beer.paa"]],
// 	["beer_gold",["Bière XXXX",0.1,"A3PL_4xGold",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\beer.paa"]],
// 	["beer_carlton",["Bière pression Carlton",0.1,"A3PL_CarltonDraught",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\beer.paa"]],
// 	["beer_coopers",["Bière Coopers",0.1,"A3PL_Coopers",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\beer.paa"]],
// 	["beer_tooheys",["Bière Tooheys",0.1,"A3PL_Tooheys",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\beer.paa"]],
// 	["beer_vb",["Bière VB",0.1,"A3PL_VBCan",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\beer.paa"]],
// 	["whiskey_jimbeam",["Whiskey Jim Beam",0.1,"A3PL_Jimbeam",20,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\whiskey.paa"]],
// 	["blueprint_balaclava",["Balaclava Blueprint",0,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprint_bandanna",["Bandanna Blueprint",0,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprint_rangemaster_belt",["Rangemaster Belt Blueprint",0,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprint_carrier_rig",["Carrier Rig Blueprint",0,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprint_shemag",["Shemag Blueprint",0,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blueprint.paa"]],
// 	["blunt",["Joint",1,"A3FL_Blunt",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\blunt.paa"]],
// 	["cigs",["Cigarettes",0.01,"cigs_morley_cig0_nv",0,true,true,true,true,true,"A3PL_Items_Cigs",[0,0,0],"",5,"po_ui\Data\items\cigarette.paa"]],
// 	["cigs_lighter",["Briquet",0.01,"cigs_lighter",0,true,true,true,true,true,"A3PL_Items_Cigs",[0,0,0],"",1,"po_ui\Data\items\lighter.paa"]],
// 	["bracelet",["Ensemble de bracelet",1,"A3FL_Jewelry_Bracelet",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\bracelet.paa"]],
// 	["bread",["Miche de pain",0.2,"A3PL_Bread",90,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\bread.paa"]],
// 	["breathalizer",["Ethylotest",0.1,"A3FL_Breathalyzer",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\breathalyzer.paa"]],
// 	["bucket_empty",["Seau vide",1,"A3PL_Bucket",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\bucket.paa"]],
// 	["bucket_full",["Seau de poissons",1,"A3PL_BucketFull",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\bucket_full.paa"]],
// 	["bulletcasing",["Douille",0.1,"A3FL_Bullet_Casings",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\bullet.paa"]],
// 	["burger_bun",["Pain à hamburger",0.5,"A3PL_Burger_Bun",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\bun.paa"]],
// 	["burger_burnt",["Poisson brûlé (Mcfishers)",0.5,"A3PL_Burger_Burnt",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cooked_fish.paa"]],
// 	["burger_cooked",["Poisson cuit",0.5,"A3PL_Burger_Cooked",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cooked_fish.paa"]],
// 	["burger_full_burnt",["Burger de poisson brûlé",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\burger.paa"]],
// 	["burger_full_cooked",["Burger de poisson cuit",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\burger.paa"]],
// 	["burger_full_raw",["Burger de poisson cru",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\burger.paa"]],
// 	["burger_raw",["Poisson cru (Mcfishers)",0.5,"A3PL_Burger_Raw",90,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\rawfish.paa"]],
// 	["c4",["Composition 4 (C4)",3,"A3FL_C4",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["calcium_carbonate",["Carbonate de calcium",0.1,"A3FL_CalciumCarbonate",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["camper_light",["Lumière de campeur",5,"A3PL_Camping_Light",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\camper_light.paa"]],
// 	["candy",["Bonbon",0.1,"A3PL_hw_candybucket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\candy.paa"]],
// 	["candycane",["Sucre d'orge",0.1,"A3FL_CandyCane",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\candycane.paa"]],
// 	["canisteroil",["Bidon de pétrole",4,"A3PL_CanisterOil",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\canister.paa"]],
// 	["cannabis_bud",["Bourgeon de cannabis",0.05,"A3PL_Cannabis_Bud",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\cannabis_bud.paa"]],
// 	["cannabis_plant",["Plante de marijuana",1.5,"A3FL_Cannabis_Plant",0,true,true,true,true,true,"",[0,2,0],"",1,"po_ui\Data\items\cannabis_plant.paa"]],
// 	["cannabis_plant_stage1",["Séchage de la plante de marijuana Étape 1",1.5,"A3FL_Cannabis_Plant_Hanging_Stage1",0,true,true,true,true,true,"",[0,0,0],"",12,"po_ui\Data\items\cannabis_plant_stage1.paa"]],
// 	["cannabis_plant_stage2",["Séchage de la plante de marijuana Étape 2",1.5,"A3FL_Cannabis_Plant_Hanging_Stage2",0,true,true,true,true,true,"",[0,0,0],"",12,"po_ui\Data\items\cannabis_plant_stage2.paa"]],
// 	["cannabis_plant_stage3",["Séchage de la plante de marijuana Étape 3",1.5,"A3FL_Cannabis_Plant_Hanging_Stage3",0,true,true,true,true,true,"",[0,0,0],"",12,"po_ui\Data\items\cannabis_plant_stage3.paa"]],
// 	["cannabis_plant_stage4",["Plante de marijuana séchée",1.5,"A3FL_Cannabis_Plant_Hanging_Stage4",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\cannabis_plant_stage4.paa"]],
// 	["tobacco",["Tabac",0.25,"A3FL_Tobacco",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\tobacco.paa"]],
// 	["carrot",["Carotte",0.5,"A3FL_Carrot",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\carrot.paa"]],
// 	["cash",["Dollars",0,"A3PL_Money",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\cash.paa"]],
// 	["cauldron",["Chaudron",10,"A3PL_hw_cauldron",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\cauldron.paa"]],
// 	["cereal",["Céréale",0.2,"A3PL_WeetBix",90,true,true,true,true,true,"A3PL_Items_Food",[-0.05,0,-0.4],"",5,"po_ui\Data\items\cereal.paa"]],
// 	["chicken",["Poulet entier",3,"A3FL_Chicken",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chicken.paa"]],
// 	["chips",["Chips",0.2,"A3FL_Chicken",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chips.paa"]],
// 	["christmas_tree",["Sapin de Noël",0.1,"A3FL_Christmas_TreeFurniture",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["coal_ingot",["Lingot de charbon",0.2,"A3PL_Ingot_Coal",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["coal_ingot_pellet",["Palette de lingots de charbon",15,"A3PL_Ingot_Pallet_Coal",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["coal_ore",["Minerai de charbon",0.25,"A3PL_Resource_Ore_Coal_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["coca",["Coca",0.5,"A3PL_Seed_Corn",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\coca.paa"]],
// 	["coca_paste",["Pâte de base de coca",0.1,"A3FL_CocaPaste",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\inventory\coca_paste.paa"]],
// 	["cocaine",["Sachet de cocaïne",1,"A3PL_PowderedMilk",15,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cocaine.paa"]],
// 	["cocaine_barrel",["Baril en plastique",30,"A3FL_PlasticBarrel",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["cocaine_base",["Base de cocaïne",0.1,"A3FL_CocainePaste",0,true,true,true,true,true,"",[0,0,0],"",3,"po_ui\Data\inventory\cocaine_base.paa"]],
// 	["cocaine_brick",["Brique de cocaïne",15,"A3FL_DrugBag",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["cocaine_hydrochloride",["Chlorhydrate de cocaïne",0.1,"A3PL_PowderedMilk",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["coffee",["Tasse à café",0.1,"A3FL_Coffee",0,true,true,true,false,false,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\coffee.paa"]],
// 	["coffee_cup_large",["Grand café",0.5,"A3FL_Coffee_Cups_Large",0,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\coffee_cup.paa"]],
// 	["coffee_cup_medium",["Café moyen",0.5,"A3FL_Coffee_Cups_Medium",0,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\coffee_cup.paa"]],
// 	["coffee_cup_small",["Petit café",0.5,"A3FL_Coffee_Cups_Small",0,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\coffee_cup.paa"]],
// 	["coke",["Soda",0.5,"A3FL_Soda",0,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\soda.paa"]],
// 	["cookies",["Cookie",0.1,"A3PL_Timtams",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cookie.paa"]],
// 	["cookingpot",["Casserole",1,"A3FL_Pot",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\pot.paa"]],
// 	["corn",["Maïs",0.5,"A3PL_CornCob",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\corn.paa"]],
// 	["cornmeal",["Semoule de maïs",3,"A3PL_Grainsack_CornMeal",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\cornmeal.paa"]],
// 	["crown",["Couronne du roi George",5,"A3FL_Jewelry_Crown",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["crude_oil",["Pétrole brut",10,"A3PL_OilBarrel",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\crude_oil.paa"]],
// 	["cyanide_pills",["Pilule de cyanure",0.1,"A3FL_CyanidePills",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\cyanide.paa"]],
// 	["diamond",["Diamant",1,"A3PL_Diamond",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_alex",["Diamant Alexandrite",0.5,"A3PL_Diamond_Alex",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_alex_ill",["Diamant Alexandrite volé",0.5,"A3PL_Diamond_Alex",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_aqua",["Diamant Aquamarine",0.5,"A3PL_Diamond_Aqua",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_aqua_ill",["Diamant Aquamarine volé",0.5,"A3PL_Diamond_Aqua",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_emerald",["Emeraude",0.5,"A3PL_Diamond_Emerald",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\emerald.paa"]],
// 	["diamond_emerald_ill",["Emeraude volé",0.5,"A3PL_Diamond_Emerald",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\emerald.paa"]],
// 	["diamond_ill",["Diamant volé",1,"A3PL_Diamond",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_ruby",["Rubis",0.5,"A3PL_Diamond_Ruby",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ruby.paa"]],
// 	["diamond_ruby_ill",["Rubis volé",0.5,"A3PL_Diamond_Ruby",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ruby.paa"]],
// 	["diamond_sapphire",["Saphir",0.5,"A3PL_Diamond_Sapphire",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sapphire.paa"]],
// 	["diamond_sapphire_ill",["Saphir volé",0.5,"A3PL_Diamond_Sapphire",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sapphire.paa"]],
// 	["diamond_tourmaline",["Diamant Tourmaline",0.5,"A3PL_Diamond_Tourmaline",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["diamond_tourmaline_ill",["Diamant Tourmaline volé",0.5,"A3PL_Diamond_Tourmaline",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\diamond.paa"]],
// 	["dildo",["Gode",0.1,"A3PL_Dildo",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\dildo.paa"]],
// 	["dirty_cash",["Argent sale",0.0005,"A3PL_Money",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\cash.paa"]],
// 	["distillery",["Distillerie",15,"A3PL_Distillery",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["distillery_hose",["Tuyau de distillerie",5,"A3PL_Distillery_Hose",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["donut_plain",["Donut (Simple)",0.1,"A3FL_Donut_Plain",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\donut.paa"]],
// 	["donut_pink",["Donut (Glaçage rose avec pépites)",0.1,"A3FL_Donut_Pink",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\donut.paa"]],
// 	["donut_choc",["Donut (Chocolat)",0.1,"A3FL_Donut_Chocolate",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\donut.paa"]],
// 	["doorkey",["Clé de porte",0.1,"A3PL_HouseKey",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\doorkey.paa"]],
// 	["drill_bit",["Foret", 3, "A3PL_Drill_Bit",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\drill_bit.paa"]],
// 	["drug_kit",["Kit de dépistage de drogue",0.1,"A3FL_DrugTest",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\drugkit.paa"]],
// 	["emerald_ingot",["Lingot d'émeraude",0.2,"A3PL_Ingot_Emerald",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["emerald_ingot_pallet",["Palette de lingots d'émeraude",15,"A3PL_Ingot_Pallet_Emerald",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["emerald_ore",["Minerai d'émeraude",0.25,"A3PL_Resource_Ore_Emerald_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["empty_ziplock",["Sac Ziplock vide",0.1,"A3FL_Drug_Bag_Empty",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ziplock.paa"]],
// 	["evidence_bag",["Sac de preuves",0.1,"A3FL_Evidence_Bag",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\evidence_bag.paa"]],
// 	["evidence_marker",["Marqueur de preuves",0.1,"A3FL_Evidence",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\evidence_marker.paa"]],
// 	["fan",["Ventilateur",5,"A3PL_Fan",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["fd_adapter",["Adaptateur de tuyau",1,"A3PL_FD_HoseEnd_Player",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\fd_adapter.paa"]],
// 	["fd_hose",["Tuyau roulé",2,"A3PL_FD_HoseRolled",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\fd_hose.paa"]],
// 	["fd_hydrantwrench",["Clé à bouche",3,"A3PL_FD_HydrantWrench",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\fd_hydrantwrench.paa"]],
// 	["fd_mask",["Masque oxygène",0.1,"A3PL_FD_Mask_Obj",180,true,true,true,true,true,"",[-0.12,-0.15,-0.73],"",1,"po_ui\Data\items\fd_mask.paa"]],
// 	["fd_yadapter",["Adaptateur Y",1,"A3PL_FD_yAdapter",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\fd_yadapter.paa"]],
// 	["fibreglass",["Fibre de glasse",1,"A3PL_Fibreglass",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\glass.paa"]],
// 	["fish_burned",["Poisson brûlé (Tacohell)",0.5,"A3PL_Fish_Burned",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cooked_fish.paa"]],
// 	["fish_cooked",["Poisson cuit",0.5,"A3PL_Fish_Cooked",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\cooked_fish.paa"]],
// 	["fish_raw",["Poisson cru (Tacohell)",1,"A3PL_Fish_Raw",0.5,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\rawfish.paa"]],
// 	["flag1",["Drapeau américain 1",15,"A3PL_Flag1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["flag2",["Drapeau américain 2",15,"A3PL_Flag2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_barcabinet",["Meuble Bar",6,"A3PL_Bar_Cabinet",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_bed1",["Lit",6,"A3PL_Bed1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_bed2",["Lit",6,"A3PL_Bed2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_bed3",["Lit",6,"A3PL_Bed3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_bookshelf",["Étagère à livres",6,"A3PL_Bookshelf",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinet1",["Étagère",6,"A3PL_Cabinet1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinet2",["Étagère",6,"A3PL_Cabinet2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinet3",["Étagère",6,"A3PL_Cabinet3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinetdoubletop",["Étagère à double porte",6,"A3PL_CabinetDoubleTop",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinetsingletop",["Étagère simple",6,"A3PL_CabinetSingleTop",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cabinettopcorner",["Étagère",6,"A3PL_CabinetTopCorner",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_chair1",["Chaise",6,"A3PL_Chair1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_chair2",["Chaise",6,"A3PL_Chair2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_chair3",["Chaise",6,"A3PL_Chair3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_chair4",["Chaise",6,"A3PL_Chair4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_coffeetable1",["Table basse",6,"A3PL_coffeeTable1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_coffeetable2",["Table basse",6,"A3PL_coffeeTable2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_coffeetable3",["Table basse",6,"A3PL_coffeeTable3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_coffeetable4",["Table basse",6,"A3PL_coffeeTable4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_cornersofa",["Canapé d'angle",6,"A3PL_CornerSova",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_countercorner",["Plan de travail d'angle",6,"A3PL_CounterCorner",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_counterdoublecabinet",["Plan de travail double",6,"A3PL_CounterDoubleCabinet",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_counterdrawer",["Tiroir",6,"A3PL_CounterDrawer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_countersinglecabinet",["Armoire unique",6,"A3PL_CounterSingleCabinet",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_countertop1",["Comptoir",6,"A3PL_CounterTop1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_countertop2",["Comptoir",6,"A3PL_CounterTop2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_countertop3",["Comptoir",6,"A3PL_CounterTop3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_diningchair",["Chaise de salle à manger",6,"A3PL_DiningChair",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_diningtableprops",["Table avec décoration",6,"A3PL_DiningTableProps",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_dryingtowel",["Porte-serviettes",6,"A3PL_DryingTowel",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_flasket",["Corbeille",6,"A3PL_Flasket",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge",["Frigo",15,"A3PL_Fridge",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_2door",["Frigo 2 Portes",15,"A3FL_Fridge_2door",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_2door_2_black",["Frigo 2 Portes 2 Noir",15,"A3FL_Fridge_2door_2_Black",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_2door_2_gray",["Frigo 2 Portes 2 Gris",15,"A3FL_Fridge_2door_2_Gray",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_2door_2_silver",["Frigo 2 Portes 2 Argent",15,"A3FL_Fridge_2door_2_Silver",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_3door",["Frigo 3 Portes",15,"A3FL_Fridge_3door",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_retro_black",["Frigo Retro Noir",15,"A3FL_Fridge_Retro_Black",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_retro_red",["Frigo Retro Rouge",15,"A3FL_Fridge_Retro_Red",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_retro_white",["Frigo Retro Blanc",15,"A3FL_Fridge_Retro_White",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_single_gray",["Frigo Single Gris",15,"A3FL_Fridge_Single_Gray",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_fridge_single_silver",["Frigo Single Argent",15,"A3FL_Fridge_Single_Silver",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_gamer_billiard",["inh",6,"A3PL_Gamer_BilliardTable",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_gamer_dartb",["inh",6,"A3PL_Gamer_Dartboard",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_gamer_galaga",["inh",6,"A3PL_Gamer_Galaga",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_gamer_lcd",["inh",6,"A3PL_Gamer_LCD",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_gamer_unicorn",["inh",6,"A3PL_Gamer_UnicornFloat",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_campfire",["inh",6,"A3PL_Garden_Campfire",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuegod2",["inh",6,"A3PL_Garden_StatueGod2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuegod3",["inh",6,"A3PL_Garden_StatueGod3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuegod4",["inh",6,"A3PL_Garden_StatueGod4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuegod",["inh",6,"A3PL_Garden_StatueGod",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuemonk",["inh",6,"A3PL_Garden_StatueMonk",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statueviking2",["inh",6,"A3PL_Garden_StatueViking2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statueviking",["inh",6,"A3PL_Garden_StatueViking",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuewoman2",["inh",6,"A3PL_Garden_StatueWoman2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuewoman3",["inh",6,"A3PL_Garden_StatueWoman3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_statuewoman",["inh",6,"A3PL_Garden_StatueWoman",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_treebench",["inh",6,"A3PL_Garden_Treebench",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_vineslarge",["inh",6,"A3PL_Garden_VinesLarge",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_vinesmedium",["inh",6,"A3PL_Garden_VinesMedium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_garden_vinessmall",["inh",6,"A3PL_Garden_VinesSmall",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_grill",["Grill",6,"A3PL_Mcfisher_Grill",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kennel",["Niche",6,"A3PL_Kennel",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenchair1",["Chaise de cuisine",6,"A3PL_KitchenChair1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenchair2",["Chaise de cuisine",6,"A3PL_KitchenChair2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenshelf1",["Étagère de cuisine",6,"A3PL_KitchenShelf1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenshelf2",["Étagère de cuisine",6,"A3PL_KitchenShelf2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenshelf3",["Étagère de cuisine",6,"A3PL_KitchenShelf3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchenshelfcorner",["Étagère d'angle de cuisine",6,"A3PL_KitchenShelfCorner",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchentable1",["Table de cuisine",6,"A3PL_KitchenTable1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_kitchentable2",["Table de cuisine",6,"A3PL_KitchenTable2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_lamp1",["Lampe",6,"A3PL_Lamp1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_lamp2",["Lampe",6,"A3PL_Lamp2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_bear",["inh",6,"A3PL_Mancave_Bearhead",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_cocktail",["inh",6,"A3PL_Mancave_CocktailSign",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_deer",["inh",6,"A3PL_Mancave_DeerAntlers",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_fox",["inh",6,"A3PL_Mancave_FoxHead",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_ghost",["inh",6,"A3PL_Mancave_GhostbusterSign",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_globe",["inh",6,"A3PL_Mancave_Globe",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_money1",["inh",6,"A3PL_Mancave_CosmeticMoney1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_money2",["inh",6,"A3PL_Mancave_CosmeticMoney2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_moose",["inh",6,"A3PL_Mancave_MooseHead",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mancave_wolf",["inh",6,"A3PL_Mancave_Wolfhead",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_mirror",["Mirroir",6,"A3PL_Mirror",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modern_dryer",["Sèche-linge Moderne",15,"A3FL_Modern_Dryer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modern_range_black",["Cuisinière Moderne Noir",15,"A3FL_Modern_Range_Black",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modern_range_red",["Cuisinière Moderne Rouge",15,"A3FL_Modern_Range_Red",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modern_range_white",["Cuisinière Moderne Blanche",15,"A3FL_Modern_Range_White",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modern_washer",["Laveuse Moderne",15,"A3FL_Modern_Washer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modkitchen1",["Armoire de cuisine",6,"A3PL_ModularKitchen1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modkitchen2",["Armoire de cuisine",6,"A3PL_ModularKitchen2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modkitchen3",["Armoire de cuisine",6,"A3PL_ModularKitchen3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_modkitchen4",["Armoire de cuisine",6,"A3PL_ModularKitchen4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_nightstand",["Table de nuit",6,"A3PL_NightStand",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_nightstandlamp",["Lampe de chevet",6,"A3PL_NightStandLamp",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_old_dryer",["Sèche-linge ancien",15,"A3FL_Old_Dryer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_old_dryer_2",["Sèche-linge ancien",15,"A3FL_Old_Dryer_2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_old_washer",["Laveuse ancienne",15,"A3FL_Old_Washer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_pouf",["Pouf",6,"A3PL_Pouf",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_rack1",["Étagère 1",6,"A3PL_Rack1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_rack2",["Étagère 2",6,"A3PL_Rack2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_range_black",["Cuisinière Noir",15,"A3FL_Range_Black",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_range_darkgray",["Cuisinière Gris Foncé",15,"A3FL_Range_DarkGray",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_range_silver",["Cuisinière Argent",15,"A3FL_Range_Silver",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sinkbigcounter",["Grand évier",6,"A3PL_SinkBigCounter",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sinksinglecabinet",["Petit évier",6,"A3PL_SinkSingleCabinet",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa1",["Sofa 1 Personne",6,"A3PL_Sofa1New",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa3",["Sofa 3 Personnes",6,"A3PL_Sofa3New",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa4",["Sofa 1",6,"A3PL_Sofa1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa5",["Sofa 2",6,"A3PL_Sofa2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa6",["Sofa 3",6,"A3PL_Sofa3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_sofa7",["Sofa 4",6,"A3PL_Sofa4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_table1",["Table 1",6,"A3PL_table1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_table2",["Table 2",6,"A3PL_table2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_television_large",["Grande Television",15,"A3FL_Television_Large",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_television_medium",["Television Moyenne",15,"A3FL_Television_Medium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_television_small",["Petite Television",15,"A3FL_Television_Small",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_tvtable1",["Meuble TV 1",6,"A3PL_TvTable1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_tvtable2",["Meuble TV 2",6,"A3PL_TvTable2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_tvtable3",["Meuble TV 3",6,"A3PL_TvTable3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_1",["inh",6,"A3PL_WallDecor_WallPanel1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_2",["inh",6,"A3PL_WallDecor_WallPanel2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_3",["inh",6,"A3PL_WallDecor_WallPanel3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_4",["inh",6,"A3PL_WallDecor_WallPanel4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_5",["inh",6,"A3PL_WallDecor_WallPanel5",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_6",["inh",6,"A3PL_WallDecor_WallPanel6",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_7",["inh",6,"A3PL_WallDecor_WallPanel7",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_8",["inh",6,"A3PL_WallDecor_WallPanel8",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_9",["inh",6,"A3PL_WallDecor_WallPanel9",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_10",["inh",6,"A3PL_WallDecor_WallPanel10",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_11",["inh",6,"A3PL_WallDecor_WallPanel11",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_12",["inh",6,"A3PL_WallDecor_WallPanel12",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_13",["inh",6,"A3PL_WallDecor_WallPanel13",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_14",["inh",6,"A3PL_WallDecor_WallPanel14",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_walldecor_15",["inh",6,"A3PL_WallDecor_WallPanel15",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_waterheater",["Chauffe-eau",15,"A3FL_WaterHeater",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_antchair",["inh",6,"A3PL_Winchester_AntiqueChair",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_antdesk",["inh",6,"A3PL_Winchester_AntiqueDesk",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_armchair",["inh",6,"A3PL_Winchester_ArmChair",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_bed1",["inh",6,"A3PL_Winchester_Bed1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_bed2",["inh",6,"A3PL_Winchester_Bed2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_bedside",["inh",6,"A3PL_Winchester_Bedside",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chair1",["inh",6,"A3PL_Winchester_Chair1",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chair2",["inh",6,"A3PL_Winchester_Chair2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw2",["inh",6,"A3PL_Winchester_ChestDrawers2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw3",["inh",6,"A3PL_Winchester_ChestDrawers3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw4",["inh",6,"A3PL_Winchester_ChestDrawers4",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw5",["inh",6,"A3PL_Winchester_ChestDrawers5",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw6",["inh",6,"A3PL_Winchester_ChestDrawers6",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw7",["inh",6,"A3PL_Winchester_ChestDrawers7",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw8",["inh",6,"A3PL_Winchester_ChestDrawers8",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw9",["inh",6,"A3PL_Winchester_ChestDrawers9",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_chestdraw",["inh",6,"A3PL_Winchester_ChestDrawers",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_drawers",["inh",6,"A3PL_Winchester_Drawers",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_floorlamp2",["inh",6,"A3PL_Winchester_Floorlamp2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_floorlamp3",["inh",6,"A3PL_Winchester_Floorlamp3",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_floorlamp",["inh",6,"A3PL_Winchester_Floorlamp",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_wardrobe",["inh",6,"A3PL_Winchester_Wardrobe",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["furn_winchester_wine",["inh",6,"A3PL_Winchester_WineBottles",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["gift",["Cadeau",0.05,"A3FL_Present",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\gift.paa"]],
// 	["girlstatue",["Statuette de fille",0.1,"Land_A3PL_Girlstatue",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["glass",["Verre",1,"A3PL_Glass",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\glass.paa"]],
// 	["glass_fibre",["Fibre de verre",1,"A3PL_Glass_Fibre",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\glass.paa"]],
// 	["gold_ingot",["Lingot d'or",0.2,"A3PL_Ingot_Gold",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["gold_ingot_pallet",["Palette de lingots d'or",15,"A3PL_Ingot_Pallet_Gold",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["gold_ore",["Minerai d'or",0.25,"A3PL_Resource_Ore_Gold_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["gold_sheet",["Feuille d'or",1,"A3PL_Sheet_Gold",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sheet.paa"]],
// 	["golden_dildo",["God doré",5,"A3FL_Jewelry_GoldenDildo",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["grinder",["Broyeur",3,"A3PL_Mixer",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["gunpowder",["Poudre à canon",1,"A3PL_Gunpowder",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\gunpowder.paa"]],
// 	["sandwich_hamcheese",["Sandwich Jambon & Fromage",0.5,"A3PL_HamCheeseSanga",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\sandwich.paa"]],
// 	["sandwich_veggie",["Sandwich Veggie",0.5,"A3PL_VegemiteSandwhich",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\sandwich.paa"]],
// 	["handcuffs",["Paire de menottes",1,"A3PL_Handcuffs",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\handcuffs.paa"]],
// 	["hoagie",["Sandwich à la viande",1,"A3FL_Hoagie",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\sandwich.paa"]],
// 	["hydrocloric_acid",["Acide hydrochlorique",0.1,"A3FL_HydroAcid",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["iron_ingot",["Lingot de fer",0.2,"A3PL_Ingot_Iron",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["iron_ingot_pellet",["Palette de lingots de fer",15,"A3PL_Ingot_Pallet_Iron",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["iron_ore",["Minerai de fer",0.25,"A3PL_Resource_Ore_Iron_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["jerrycan",["Bidon d'essence",10,"A3PL_Jerrycan",-90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jerrycan.paa"]],
// 	["jerrycan_empty",["Bidon d'essence vide",1,"A3PL_Jerrycan",-90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jerrycan_empty.paa"]],
// 	["jobcargo",["Caisse de fret",500,"A3PL_Crate",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\box.paa"]],
// 	["jug",["Cruche",3,"A3PL_Jug",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jug.paa"]],
// 	["jug_green",["Cruche (Verte)",3,"A3PL_Jug_Green",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jug.paa"]],
// 	["jug_green_moonshine",["Cruche (contient de l'alcool à la pomme)",5,"A3PL_Jug_Green_Corked",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jug_moonshine.paa"]],
// 	["jug_moonshine",["Cruche de Moonshine",3,"A3PL_Jug_Corked",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\jug_moonshine.paa"]],
// 	["kerosene",["Kerosene",10,"A3PL_Kerosene",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\kerosene.paa"]],
// 	["kerosene_jerrycan",["Bidon de kerosene",10,"A3PL_Jerrycan",-90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\kerosene_jerrycan.paa"]],
// 	["kevlar",["Kevlar",1,"A3PL_Kevlar",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\kevlar.paa"]],
// 	["keycard",["Carte d'accès",0.01,"A3FL_Keycard",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\keycard.paa"]],
// 	["ladder",["Echelle",5,"A3PL_Ladder",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["lamington",["Lamington",0.1,"A3PL_Lamington",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\lamington.paa"]],
// 	["lamp_200w",["Lampe 200W",5,"A3PL_Cannabis_Lamp_200W",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["lamp_500w",["Lampe 500W",5,"A3PL_Cannabis_Lamp_500W",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["lamp_1000w",["Lampe 1000W",5,"A3PL_Cannabis_Lamp_1000W",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["lantern",["Lanterne",0.1,"A3PL_hw_lantern",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\lantern.paa"]],
// 	["lettuce",["Salade",0.5,"A3PL_LettuceItem",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\lettuce.paa"]],
// 	["life_alert",["Urgence médicale",0.1,"A3FL_LifeAlert",0.005,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\life_alert.paa"]],
// 	["lifebuoy",["Bouée de sauvetage",1,"A3PL_Lifebuoy",0,true,true,true,true,true,"",[0.3,-0.2,-0.3],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["log",["Rondin de bois",2,"A3PL_WoodenLog",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["woodpl",["Planche de bois",2,"A3PL_WoodenLog",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\woodpl.paa"]],
// 	["lpg",["LPG",5,"A3PL_LPG",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["mail",["Courrier",0.2,"A3PL_DeliveryBox",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\box.paa"]],
// 	["malt",["Malt",3,"A3PL_Grainsack_Malt",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\malt.paa"]],
// 	["marijuana",["Marijuana (OLD)",1,"A3PL_MarijuanaBag",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\cannabis_bud.paa"]],
// 	["matches",["Allumettes",0.5,"A3PL_Seed_Corn",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\matches.paa"]],
// 	["me_bucket",["Godet d'excavatrice",0,"A3PL_MiniExcavator_Bucket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\me_bucket.paa"]],
// 	["me_jackhammer",["Marteau-piqueur",0,"A3PL_MiniExcavator_Jackhammer",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\me_jackhammer.paa"]],
// 	["meat_boar",["Viande de sanglier",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\meat.paa"]],
// 	["meat_boar_tag",["Viande de sanglier (Etiquetée)",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_pork_tranched",["Tranche de viande de porc",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_beef_tranched",["Tranche de viande de boeuf",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_agneau_tranched",["Tranche de viande d'agneau",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_firstprice_tranched",["Tranche de viande de 1er prix",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_cow",["Boeuf",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\meat.paa"]],
// 	["meat_cow_tag",["Boeuf (Etiquetée)",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_goat",["Viande de chèvre",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\meat.paa"]],
// 	["meat_goat_tag",["Viande de chèvre (Etiquetée)",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_scraps",["Restes de viande",0.5,"A3PL_Burger_Raw",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meat_sheep",["Viande de mouton",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\meat.paa"]],
// 	["meat_sheep_tag",["Viande de mouton (Etiquetée)",0.5,"A3PL_Steak",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\meat.paa"]],
// 	["meatpie",["Tourte à la viande",0.5,"A3PL_MeatPie",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\meatpie.paa"]],
// 	["med_autograftkit",["Kit de greffe de peau",0.05,"A3PL_Medical_Kit",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_autograftkit.paa"]],
// 	["med_autograft",["Greffe de peau",0.05,"A3PL_Medical_Kit",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_autograftkit.paa"]],
// 	["med_bandage",["Bandage",0.05,"A3PL_Bandage",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_bandage.paa"]],
// 	["med_cast",["Plâtre",0.05,"A3PL_Medical_Cast",0.05,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_cast.paa"]],
// 	["med_endotracheal",["Endotrachéal",0.025,"A3PL_Medical_Endotracheal",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_endotracheal.paa"]],
// 	["med_eyewash",["Solution de lavage oculaire",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\painkiller.paa"]],
// 	["med_icepack",["Pack de glace",0.05,"A3PL_Medical_Icepack",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_icepack.paa"]],
// 	["med_kit",["Trousse chirurgicale",0.05,"A3PL_Medical_Kit",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_kit.paa"]],
// 	["med_narcan",["Naloxone",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_narcan.paa"]],
// 	["med_oxygenmask",["Oxygène",0.05,"A3PL_Medical_OxygenMask",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_oxygenmask.paa"]],
// 	["med_painkillers",["Analgésiques",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_painkillers.paa"]],
//     ["med_antistress",["Calmant",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_antistress.paa"]],
// 	["med_splint",["Attelle",0.08,"A3PL_Medical_Splint",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_splint.paa"]],
// 	["meds_bloodbag",["Poche de sang",0.05,"A3PL_BloodBag",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_bloodbag.paa"]],
// 	["meds_bloodbagempty",["Poche de sang vide",0.05,"A3PL_BloodBag",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\med_bloodbagempty.paa"]],
// 	["mullet",["Mulet",0.5,"A3PL_Mullet",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\mullet.paa"]],
// 	["mullet_tag",["Mulet (Etiquetée)",0.5,"A3PL_Mullet",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\mullet_tag.paa"]],
// 	["necklace",["Collier de perles",0.5,"A3FL_Jewelry_Necklace",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\necklace.paa"]],
// 	["net",["Filet de pêche",1,"A3PL_FishingBuoy",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\net.paa"]],
// 	["nylon",["Nylon",0.2,"A3PL_Nylon",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\nylon.paa"]],
// 	["pavilion",["Pavillon",0.1,"A3PL_Pavilion",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["petrol",["Pétrole raffiné",10,"A3PL_OilBarrel",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pizzabites",["Bouchée de pizza",0.1,"A3PL_PartyPack",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\pizza.paa"]],
// 	["planter",["Jardinière",10,"A3PL_Planter2",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["plastic",["Plastique",1,"A3PL_Plastic",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\plastic.paa"]],
// 	["plastic_barrier_large",["Grande barrière en plastique",3,"A3PL_PlasticBarrier_02",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["plastic_barrier_small",["Petite barrière en plastique",3,"A3PL_PlasticBarrier_01",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["polyester",["Polyester",1,"A3PL_Polyester",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\polyester.paa"]],
// 	["popcornbucket",["Seau de pop-corn",0.5,"A3PL_PopcornBucket",0,false,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\popcorn.paa"]],
// 	["potassium_permangate",["Permanganate de potassium",0.1,"A3FL_Potassium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["powdertestkit",["Kit de test de poudre à canon",0.1,"A3FL_DrugTest",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\powdertestkit.paa"]],
// 	["pumpjack",["Extracteur de pétrole",20,"A3PL_Pumpjack",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\box.paa"]],
// 	["pumpkin_green",["Citrouille verte",0.1,"Land_A3PL_hw_pumpkin_green",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pumpkin_orange",["Citrouille orange",0.1,"Land_A3PL_hw_pumpkin_orange",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pumpkin_red",["Citrouille rouge",0.1,"Land_A3PL_hw_pumpkin_red",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pumpkinhat_green",["Chapeau de citrouille vert",0.1,"Land_A3PL_hw_pumpkinhat_green",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pumpkinhat_orange",["Chapeau de citrouille orange",0.1,"Land_A3PL_hw_pumpkinhat_orange",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["pumpkinhat_red",["Chapeau de citrouille rouge",0.1,"Land_A3PL_hw_pumpkinhat_red",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["repairwrench",["Clé de réparation",1,"A3PL_Wrench",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\repairwrench.paa"]],
// 	["ring",["Bague",0.5,"A3FL_Jewelry_Ring",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ring.paa"]],
// 	["ringset",["Ensemble de bagues",1,"A3FL_Jewelry_RingSet",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ringset.paa"]],
// 	["roadcone",["Cône",1,"A3PL_RoadCone",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["roadcones",["Pile de cônes (x10)",10,"A3PL_RoadCone_x10",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["rocket_blue",["Feux d'artifice (bleu)",2,"A3PL_Rocket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\firework.paa"]],
// 	["rocket_green",["Feux d'artifice (vert)",2,"A3PL_Rocket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\firework.paa"]],
// 	["rocket_red",["Feux d'artifice (rouge)",2,"A3PL_Rocket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\firework.paa"]],
// 	["rocket_yellow",["Feux d'artifice (jaune)",2,"A3PL_Rocket",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\firework.paa"]],
// 	["rubber",["Caoutchouc",0.2,"A3PL_Rubber",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\rubber.paa"]],
// 	["salad",["Sachet de salade",0.5,"A3PL_Salad",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\salad.paa"]],
// 	["sand",["Sable",1,"A3PL_BucketSand",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sandbucket.paa"]],
// 	["sapphire_ingot",["Lingot de saphir",0.2,"A3PL_Ingot_Sapphire",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["sapphire_ingot_pallet",["Palette de lingots de saphir",15,"A3PL_Ingot_Pallet_Sapphire",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["sapphire_ore",["Minerai de saphir",0.25,"A3PL_Resource_Ore_Sapphire_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["sausages",["Saucisse",0.1,"A3PL_Sausages",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\sausages.paa"]],
// 	["scale",["Balance",3,"A3PL_Scale",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["scene_light",["Lumière de scène",5,"A3PL_SceneLight",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["seed_coca",["Graine de coca",0.5,"A3PL_Seed_Coca",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_corn",["Graine de maïs",0.5,"A3PL_Seed_Corn",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_lettuce",["Graine de laitue",0.5,"A3PL_Seed_Lettuce",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_marijuana",["Graine de marijuana",0.5,"A3PL_Seed_Marijuana",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_tobacco",["Graine de tabac",0.5,"A3PL_Seed_Tobacco",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_sugar",["Graine de canne à sucre",0.5,"A3PL_Seed_Sugarcane",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_wheat",["Graine de blé",0.5,"A3PL_Seed_Wheat",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["seed_carrot",["Graines de carotte",0.5,"A3PL_Seed_Carrot",0,true,true,true,true,true,"",[0,0,0],"",10,"po_ui\Data\items\seeds.paa"]],
// 	["shark_2lb",["Requin - 2LB",2,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\shark.paa"]],
// 	["shark_2lb_tag",["Requin - 2LB (Etiquetée)",2,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\shark.paa"]],
// 	["shark_4lb",["Requin - 4LB",4,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\shark.paa"]],
// 	["shark_4lb_tag",["Requin - 4LB (Etiquetée)",4,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\shark.paa"]],
// 	["shark_5lb",["Requin - 5LB",5,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\shark.paa"]],
// 	["shark_5lb_tag",["Requin - 5LB (Etiquetée)",5,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\.sharkpaa"]],
// 	["shark_7lb",["Requin - 7LB",7,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\shark.paa"]],
// 	["shark_7lb_tag",["Requin - 7LB (Etiquetée)",7,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\shark.paa"]],
// 	["shark_10lb",["Requin - 10LB",10,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\shark.paa"]],
// 	["shark_10lb_tag",["Requin - 10LB (Etiquetée)",10,"A3PL_CatShark",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\shark.paa"]],
// 	["shrooms",["Champignon",0.5,"A3FL_Mushroom",15,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\shroom.paa"]],
// 	["skeletoncauldron",["Squelette avec chaudron",0.1,"Land_A3PL_hw_skeletonCauldron",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["soupcup",["Ragoût d'agneau",0.1,"A3PL_MaggiiNoodle",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\stew.paa"]],
// 	["soup",["Soupe",0.1,"A3PL_MaggiiNoodle",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\soup.paa"]],
// 	["spandex",["Fibre synthétique élastique",0.2,"A3PL_Spandex",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\spandex.paa"]],
// 	["steel",["Acier",1,"A3PL_Steel",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sheet.paa"]],
// 	["steel_pellet",["Palette d'acier",15,"A3PL_Pallet_Steel",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["stinger",["Herse",3,"A3FL_Stinger",0,true,true,true,true,true,"",[2,0.5,0],"",1,"po_ui\Data\items\stinger.paa"]],
// 	["stretcher",["Brancard",100,"A3FL_Stretcher",0.005,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["wheelchair",["Fauteil roulant",100,"A3FL_Wheelchair",0.005,true,true,true,true,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["bin",["Poubelle",100,"A3FL_Stretcher",0.005,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["sugarcane",["Canne à sucre",0.5,"A3PL_Seed_Corn",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\sugarcane.paa"]],
// 	["sulphur_ore",["Minerai de soufre",0.25,"A3PL_Resource_Ore_Suphur_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["sulphur_powder",["Poudre sulfurique",1,"A3PL_SulphurPowder",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\powder.paa"]],
// 	["sulphuric_acid",["Acide sulfurique",0.1,"A3FL_SulphuricAcid",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\chemical.paa"]],
// 	["swishers",["Feuille OCB",0.1,"A3FL_Swishers",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\swishers.paa"]],
// 	["synthetic_fibre",["Fibre synthétique",0.2,"A3PL_Synthetic_Fiber",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\synthetic_fibre.paa"]],
// 	["table",["Table",10,"A3FL_Table",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["taco_burned",["Tacos au poisson brûlé",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\tacos.paa"]],
// 	["taco_cooked",["Tacos au poisson cuit",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\tacos.paa"]],
// 	["taco_raw",["Tacos au poisson cru",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\tacos.paa"]],
// 	["tacoshell",["Tortilla",0.5,"A3PL_TacoShell",0,true,true,true,true,true,"A3PL_Items_Food",[0,0,0],"",5,"po_ui\Data\items\tortilla.paa"]],
// 	["tag_fish",["Étiquette de poisson",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\tag.paa"]],
// 	["tag_meat",["Étiquette de viande",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\tag.paa"]],
// 	["tag_shark",["Étiquette de requin",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\tag.paa"]],
// 	["ticket",["Procès-Verbal",0.1,"A3PL_Ticket",0,false,false,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["titanium",["Titanium",1,"A3PL_Titanium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\sheet.paa"]],
// 	["titanium_ingot",["Lingot de titanium",0.5,"A3PL_Ingot_Titanium",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["titanium_ingot_pellet",["Palette de lingots de titanium",15,"A3PL_Ingot_Pallet_Titanium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["titanium_ore",["Minerai de titanium",0.25,"A3PL_Resource_Ore_Titanium_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["titanium_pellet",["Palette de titanium",15,"A3PL_Pallet_Titanium",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["toolbox",["Boîte à outils",6,"A3FL_Toolbox",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["turtle",["Tortue",5,"A3PL_Ornate",90,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\turtle.paa"]],
// 	["tyres",["Pneu",4,"A3PL_Tyre",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\tire.paa"]],
// 	["usb_stick",["Clé USB",0.5,"A3FL_USB_Stick",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\usb_drive.paa"]],
// 	["v_lockpick",["Outil de crochetage",0.1,"A3PL_Lockpick",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\lockpick.paa"]],
// 	["vivianite_ingot",["Lingot de vivianite",0.2,"A3PL_Ingot_Vivianite",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ingot.paa"]],
// 	["vivianite_ingot_pallet",["Palette de lingots de vivianite",15,"A3PL_Ingot_Pallet_Vivianite",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\pellet.paa"]],
// 	["vivianite_ore",["Minerai de vivianite",0.25,"A3PL_Resource_Ore_Vivianite_Small",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\ore.paa"]],
// 	["waterbottle",["Bouteille d'eau",0.5,"A3PL_BottlePlastic_V2",0,true,true,true,true,true,"A3PL_Items_Thirst",[0,0,0],"",5,"po_ui\Data\items\waterbottle.paa"]],
// 	["waterbottlempty",["Bouteille d'eau vide",0.1,"A3PL_BottlePlastic_V2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\waterbottleempty.paa"]],
// 	["weed_bag_5g",["Marijuana en sachet (5 grammes)",1,"A3FL_Weed_Bag_5g",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_bag_5g.paa"]],
// 	["weed_bag_10g",["Marijuana en sachet (10 grammes)",1,"A3FL_Weed_Bag_10g",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_bag_10g.paa"]],
// 	["weed_bag_25g",["Marijuana en sachet (25 grammes)",2,"A3FL_Weed_Bag_25g",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_bag_25g.paa"]],
// 	["weed_bag_50g",["Marijuana en sachet (50 grammes)",2,"A3FL_Weed_Bag_50g",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_bag_50g.paa"]],
// 	["weed_bag_100g",["Marijuana en sachet (100 grammes)",2,"A3FL_Weed_Bag_100g",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_bag_100g.paa"]],
// 	["weed_grinded_empty",["Boite vide",1,"A3FL_Grinded_Marijuana_Empty",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_empty.paa"]],
// 	["weed_grinded_5",["Boîte de marijuana broyée (5g)",2,"A3FL_Grinded_Marijuana_5",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_5.paa"]],
// 	["weed_grinded_10",["Boîte de marijuana broyée (10g)",2,"A3FL_Grinded_Marijuana_10",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_10.paa"]],
// 	["weed_grinded_15",["Boîte de marijuana broyée (15g)",2,"A3FL_Grinded_Marijuana_15",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_15.paa"]],
// 	["weed_grinded_20",["Boîte de marijuana broyée (20g)",2,"A3FL_Grinded_Marijuana_20",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_20.paa"]],
// 	["weed_grinded_25",["Boîte de marijuana broyée (25g)",2,"A3FL_Grinded_Marijuana_25",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_25.paa"]],
// 	["weed_grinded_30",["Boîte de marijuana broyée (30g)",2,"A3FL_Grinded_Marijuana_30",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_30.paa"]],
// 	["weed_grinded_35",["Boîte de marijuana broyée (35g)",2,"A3FL_Grinded_Marijuana_35",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_35.paa"]],
// 	["weed_grinded_40",["Boîte de marijuana broyée (40g)",2,"A3FL_Grinded_Marijuana_40",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_40.paa"]],
// 	["weed_grinded_45",["Boîte de marijuana broyée (45g)",2,"A3FL_Grinded_Marijuana_45",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_45.paa"]],
// 	["weed_grinded_50",["Boîte de marijuana broyée (50g)",2,"A3FL_Grinded_Marijuana_50",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_50.paa"]],
// 	["weed_grinded_55",["Boîte de marijuana broyée (55g)",2,"A3FL_Grinded_Marijuana_55",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_55.paa"]],
// 	["weed_grinded_60",["Boîte de marijuana broyée (60g)",2,"A3FL_Grinded_Marijuana_60",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_60.paa"]],
// 	["weed_grinded_65",["Boîte de marijuana broyée (65g)",2,"A3FL_Grinded_Marijuana_65",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_65.paa"]],
// 	["weed_grinded_70",["Boîte de marijuana broyée (70g)",2,"A3FL_Grinded_Marijuana_70",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_70.paa"]],
// 	["weed_grinded_75",["Boîte de marijuana broyée (75g)",2,"A3FL_Grinded_Marijuana_75",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_75.paa"]],
// 	["weed_grinded_80",["Boîte de marijuana broyée (80g)",2,"A3FL_Grinded_Marijuana_80",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_80.paa"]],
// 	["weed_grinded_85",["Boîte de marijuana broyée (85g)",2,"A3FL_Grinded_Marijuana_85",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_85.paa"]],
// 	["weed_grinded_90",["Boîte de marijuana broyée (90g)",2,"A3FL_Grinded_Marijuana_90",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_90.paa"]],
// 	["weed_grinded_95",["Boîte de marijuana broyée (95g)",2,"A3FL_Grinded_Marijuana_95",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_95.paa"]],
// 	["weed_grinded_100",["Boîte de marijuana broyée (100g)",2,"A3FL_Grinded_Marijuana_100",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\weed_grinded_100.paa"]],
// 	["weed_rack",["Étendoir",5,"A3FL_Weed_Rack",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["wheat",["Blé",0.1,"A3PL_Sack",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\wheat.paa"]],
// 	["windows",["Fenêtre",5,"A3PL_Glass",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\glass.paa"]],
// 	["wood_barrier",["Barrière en bois",3,"A3PL_RoadBarrier",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["workbench",["Table de travail",10,"A3PL_WorkBench",0,true,true,true,false,true,"",[0,0,0],"",1,"po_ui\Data\inventory\placeholder.paa"]],
// 	["yeast",["Levure",3,"A3PL_Grainsack_Yeast",0,true,true,true,false,false,"",[0,0,0],"",1,"po_ui\Data\items\yeast.paa"]],
// 	["zipties",["Zipties",1,"A3PL_Ziptie",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\items\zipties.paa"]],
// 	["blueprint_fisd",["Plan de fabrication FISD",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprinteq_fisd",["Plan de fabrication de munitions FISD",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\blueprint.paa"]],
// 	["blueprint_fifr",["Plan de fabrication FIFR",0.1,"A3PL_File2",0,true,true,true,true,true,"",[0,0,0],"",5,"po_ui\Data\items\blueprint.paa"]]
// ];
// publicVariable "Config_ItemMap";

// Config_CombineItems =
// [
// 	["burger_full_cooked",["burger_cooked","burger_bun","Salad"],1],
// 	["taco_cooked",["fish_cooked","tacoshell","Salad"],1]
// ];
// publicVariable "Config_CombineItems";

/*
	["ethanol",["Ethanol",0.5,"A3FL_Ethanol",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\.paa"]],
	["rdx",["Royal Demolition Explosive",0.5,"A3FL_RDX",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\.paa"]],
	["c4",["Composition 4 (C4)",3,"A3FL_C4",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\.paa"]],
	["synthrubber",["Synthetic Rubber",0.5,"A3PL_Rubber",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\.paa"]],
	["explosivemix",["Explosive Mix",0.5,"A3FL_ExploMix",0,true,true,true,true,true,"",[0,0,0],"",1,"po_ui\Data\inventory\.paa"]],
	["explosive_barrel",["Explosive Barrel",30,"A3FL_ExplosiveBarrel",0,true,true,true,false,false,"",[0,0,0],"",1]]
*/
