/*
    Code written by NORTHBRIDGE INTERACTIVE
	58, RUE DE MONCEAU, 75008 PARIS, FRANCE
	SIRET : 93008862000016 
    @Copyright NORTHBRIDGE INTERACTIVE (https://northbridgeinteractive.com)
    YOU ARE NOT ALLOWED TO COPY OR DISTRIBUTE THE CONTENT OF THIS FILE WITHOUT AUTHOR AGREEMENT
    More informations : https://www.bistudio.com/community/game-content-usage-rules
    Contact : contact@northbridgeinteractive.com
*/
//["factory_ID","classname","type",time,[["required",3],["components",200]],output,xpGain,levelRequired,description]
Config_Factories = [
	["Admin Tools",[0,0,0],
	    ["f_MCS_Boss","A3PL_MCS_Boss","vest",0,[],1,""],
		["f_MCS_Member","A3PL_MCS_Member","vest",0,[],1,""],
		["f_FBI_Suit_Tie_Uniform","A3PL_FBI_Suit_Tie_Uniform","uniform",0,[],1,""],
		["f_FBI_Agent_Blue_Uniform","A3PL_FBI_Agent_Blue_Uniform","uniform",0,[],1,""],
		["f_FBI_Agent_Tan_Uniform","A3PL_FBI_Agent_Tan_Uniform","uniform",0,[],1,""],
		["f_FBI_Trainee","A3PL_FBI_Trainee","vest",0,[],1,""],
		["f_FBI_Executive","A3PL_FBI_Executive","vest",0,[],1,""],
		["f_FBI_Supervisor","A3PL_FBI_Supervisor","vest",0,[],1,""],
		["f_FBI_Ballcap3","A3PL_FBI_Ballcap3","headgear",0,[],1,""],
		["f_candy","candy","item",0,[],1,""],
		["f_gift","gift","item",0,[],1,""],
		["f_ItemGPS","ItemGPS","aitem",0,[],1,""],
		["f_ItemMap","ItemMap","aitem",0,[],1,""],
		["f_life_alert","life_alert","item",0,[],1,""],
		["f_drill_bit","drill_bit","item",0,[],1,""],
		["f_Backpack_Drill","A3PL_Backpack_Drill","backpack",0,[],1,""],
		["f_Backpack_Money","A3PL_Backpack_Money","backpack",0,[],1,""],
		["f_keycard","keycard","item",0,[],1,""],
		["f_usb_stick","usb_stick","item",0,[],1,""],
		["f_beer","beer","item",0,[],1,""],
		["f_sand","sand","item",0,[],1,""],
		["f_Aluminium_Ore","Aluminium_Ore","item",0,[],1,""],
		["f_Sulphur_Ore","Sulphur_Ore","item",0,[],1,""],
		["f_Iron_Ore","Iron_Ore","item",0,[],1,""],
		["f_Coal_Ore","Coal_Ore","item",0,[],1,""],
		["f_Sapphire_Ore","Sapphire_Ore","item",0,[],1,""],
		["f_Vivianite_Ore","Vivianite_Ore","item",0,[],1,""],
		["f_Emerald_Ore","Emerald_Ore","item",0,[],1,""],
		["f_Gold_Ore","Gold_Ore","item",0,[],1,""],
		["f_Amethyst_Ore","Amethyst_Ore","item",0,[],1,""],
		["f_diamond_emerald","diamond_emerald","item",0,[],1,""],
		["f_diamond_sapphire","diamond_sapphire","item",0,[],1,""],
		["f_diamond_aqua","diamond_aqua","item",0,[],1,""],
		["f_diamond_alex","diamond_alex","item",0,[],1,""],
		["f_diamond_ruby","diamond_ruby","item",0,[],1,""],
		["f_diamond_tourmaline","diamond_tourmaline","item",0,[],1,""],
		["f_diamond","diamond","item",0,[],1,""],
		["f_seed_marijuana","seed_marijuana","item",0,[],1,""],
		["f_weed_bag_5g","weed_bag_5g","item",0,[],1,""],
		["f_weed_bag_10g","weed_bag_10g","item",0,[],1,""],
		["f_weed_bag_25g","weed_bag_25g","item",0,[],1,""],
		["f_weed_bag_50g","weed_bag_50g","item",0,[],1,""],
		["f_weed_bag_100g","weed_bag_100g","item",0,[],1,""],
		["f_cannabis_plant_stage1","cannabis_plant_stage1","item",0,[],1,""],
		["f_cannabis_plant_stage2","cannabis_plant_stage2","item",0,[],1,""],
		["f_cannabis_plant_stage3","cannabis_plant_stage3","item",0,[],1,""],
		["f_cannabis_plant_stage4","cannabis_plant_stage4","item",0,[],1,""],
		["f_cocaine","cocaine","item",0,[],1,""],
		["f_scale","scale","item",0,[],1,""],
		["f_fan","fan","item",0,[],1,""],
		["f_grinder","grinder","item",0,[],1,""],
		["f_planter","planter","item",0,[],1,""],
		["f_lamp_200w","lamp_200w","item",0,[],1,""],
		["f_lamp_500w","lamp_500w","item",0,[],1,""],
		["f_lamp_1000w","lamp_1000w","item",0,[],1,""],
		["f_weed_rack","weed_rack","item",0,[],1,""],
		["f_blunt","blunt","item",0,[],1,""],
		["f_swishers","swishers","item",0,[],1,""],
		["f_pavilion","pavilion","item",0,[],1,""],
		["f_workbench","workbench","item",0,[],1,""],
		["f_cocaine_barrel","cocaine_barrel","item",0,[],1,""],
		["f_sulphuric_acid","sulphuric_acid","item",0,[],1,""],
		["f_calcium_carbonate","calcium_carbonate","item",0,[],1,""],
		["f_potassium_permangate","potassium_permangate","item",0,[],1,""],
		["f_ammonium_hydroxide","ammonium_hydroxide","item",0,[],1,""],
		["f_acetone","acetone","item",0,[],1,""],
		["f_hydrocloric_acid","hydrocloric_acid","item",0,[],1,""],
		["f_coca_paste","coca_paste","item",0,[],1,""],
		["f_cocaine_base","cocaine_base","item",0,[],1,""],
		["f_cocaine_hydrochloride","cocaine_hydrochloride","item",0,[],1,""],
		["f_cocaine_brick","cocaine_brick","item",0,[],1,""],
		["f_shrooms","shrooms","item",0,[],1,""],
		["f_turtle","turtle","item",0,[],1,""],
		["f_cornmeal","cornmeal","item",0,[],1,""],
		["f_malt","malt","item",0,[],1,""],
		["f_yeast","yeast","item",0,[],1,""],
		["f_distillery","distillery","item",0,[],1,""],
		["f_distillery_hose","distillery_hose","item",0,[],1,""],
		["f_jug","jug","item",0,[],1,""],
		["f_jug_green","jug_green","item",0,[],1,""],
		["f_jug_moonshine","jug_moonshine","item",0,[],1,""],
		["f_diamond_emerald_ill","diamond_emerald_ill","item",0,[],1,""],
		["f_diamond_sapphire_ill","diamond_sapphire_ill","item",0,[],1,""],
		["f_diamond_aqua_ill","diamond_aqua_ill","item",0,[],1,""],
		["f_diamond_alex_ill","diamond_alex_ill","item",0,[],1,""],
		["f_diamond_ruby_ill","diamond_ruby_ill","item",0,[],1,""],
		["f_diamond_tourmaline_ill","diamond_tourmaline_ill","item",0,[],1,""],
		["f_Crude_Oil","Crude_Oil","item",0,[],1,""],
		["f_diamond_ill","diamond_ill","item",0,[],1,""],
		["f_ring","ring","item",0,[],1,""],
		["f_ringset","ringset","item",0,[],1,""],
		["f_bracelet","bracelet","item",0,[],1,""],
		["f_crown","crown","item",0,[],1,""],
		["f_necklace","necklace","item",0,[],1,""],
		["f_bucket_full","bucket_full","item",0,[],1,""],
		["f_shark_2lb","shark_2lb","item",0,[],1,""],
		["f_shark_4lb","shark_4lb","item",0,[],1,""],
		["f_shark_5lb","shark_5lb","item",0,[],1,""],
		["f_shark_7lb","shark_7lb","item",0,[],1,""],
		["f_shark_10lb","shark_10lb","item",0,[],1,""],
		["f_tag_fish","tag_fish","item",0,[],1,""],
		["f_burger_cooked","burger_cooked","item",0,[],1,""],
		["f_fish_cooked","fish_cooked","item",0,[],1,""],
		["f_seed_corn","seed_corn","item",0,[],5,""],
		["f_seed_wheat","seed_wheat","item",0,[],5,""],
		["f_seed_lettuce","seed_lettuce","item",0,[],5,""],
		["f_seed_coca","seed_coca","item",0,[],5,""],
		["f_seed_sugar","seed_sugar","item",0,[],5,""],
		["f_wheat","wheat","item",0,[],5,""],
		["f_corn","corn","item",0,[],5,""],
		["f_lettuce","lettuce","item",0,[],5,""],
		["f_Burger","burger_full_cooked","item",0,[],5,""],
		["f_Taco","taco_cooked","item",0,[],5,""],
		["f_waterbottle","waterbottle","item",0,[],5,""],
		["f_mullet","mullet","item",0,[],5,""],
		["f_cyanide_pills","cyanide_pills","item",0,[],1,""],
		["f_matches","matches","item",0,[],5,""],
		["f_zipties","zipties","item",0,[],1,""],
		["f_v_lockpick","v_lockpick","item",0,[],1,""],
		["f_furn_grill","furn_grill","item",0,[],1,""],
		["f_furn_sinksinglecabinet","furn_sinksinglecabinet","item",0,[],1,""],
		["f_Paintball_Marker","A3PL_Paintball_Marker","weapon",60,[],1,""],
		["f_Paintball_Mag","A3PL_Paintball_Mag","magazine",60,[],10,""],
		["f_Pickaxe","A3PL_Pickaxe","weapon",60,[],1,""],
		["f_Shovel","A3PL_Shovel","weapon",60,[],1,""],
		["f_GolfDriver","A3FL_GolfDriver","weapon",60,[],1,""],
		["f_BaseballBat","A3FL_BaseballBat","weapon",60,[],1,""],
		["f_DickStick","A3FL_DickStick","weapon",60,[],1,""],
		["f_DickStickGold","A3FL_DickStickGold","weapon",60,[],1,""],
		["f_anprc152","tfar_anprc152","aitem",0,[],1,""],
		["f_explosive_barrel","A3FL_ExplosiveBarrel","item",0,[],1,""]
	],

    ["STR_Common_FactoryName_Jewelry",[9983.55,8496.61,0],
        ["f_Chain1","A3FL_Chain1","item",0,[["Petrol",1]],1,""],
        ["f_Earing1","A3FL_Earing1","item",0,[["Petrol",1]],1,""],
        ["f_Nosering1","A3FL_Nosering1","item",0,[["Petrol",1]],1,""],
        ["f_ringset","ringset","item",0,[["Petrol",1]],1,""],
        ["f_ring","ring","item",0,[["Petrol",1]],1,""],
        ["f_bracelet","bracelet","item",0,[["Petrol",1]],1,""],
        ["f_crown","crown","item",0,[["Petrol",1]],1,""],
        ["f_necklace","necklace","item",0,[["Petrol",1]],1,""],
        ["f_golden_dildo","golden_dildo","item",0,[["Petrol",1]],1,""]
    ],

	["STR_Common_FactoryName_Chimical",[9983.55,8496.61,0],
		["f_Synthetic_Fiber","Synthetic_Fibre","item",5,[["Petrol",1]],50,"Craft x50"],
		["f_Glass_Fiber","Glass_Fibre","item",5,[["Sand",1]],50,"Craft x50"],
		["f_Titanium_Ore","Titanium_Ore","item",15,[["Sand",1]],8,"Craft x4"],
		["f_Polyester","Polyester","item",10,[["Synthetic_Fibre",5]],1,"Craft x1"],
		["f_Rubber","Rubber","item",10,[["Synthetic_Fibre",5]],1,"Craft x1"],
		["f_Fibreglass","Fibreglass","item",10,[["Glass_Fibre",10]],1,"Craft x1"],
		["f_Plastic","Plastic","item",5,[["Petrol",1]],20,"Craft x20"],
		["f_waterbottlempty","waterbottlempty","item",5,[["Plastic",1]],1,"Craft x1"],
		["f_Sulphur_Powder","Sulphur_Powder","item",5,[["Sulphur_Ore",1]],2,"Craft x2"],
		["f_gunpowder","Gunpowder","item",5,[["Sulphur_Powder",5],["Coal_Ingot",2]],5,"Craft x5"],
		["f_Glass","Glass","item",5,[["Glass_Fibre",5]],1,"Craft x1"],
		["f_Titanium_Ingot","Titanium_Ingot","item",55,[["Titanium_Ingot_Pellet",1]],256,"Craft x256"],
		["f_Iron_Ingot","Iron_Ingot","item",25,[["Iron_Ingot_Pellet",1]],256,"Craft x256"],
		["f_Coal_Ingot","Coal_Ingot","item",10,[["Coal_Ingot_Pellet",1]],256,"Craft x256"],
		["f_Aluminium_IngotS","Aluminium_Ingot","item",40,[["Aluminium_Ingot_Pellet",1]],256,"Craft x256"],
		["f_Sapphire_Ingot","Sapphire_Ingot","item",60,[["Sapphire_Ingot_Pallet",1]],256,"Craft x256"],
		["f_Vivianite_Ingot","Vivianite_Ingot","item",55,[["Vivianite_Ingot_Pallet",1]],256,"Craft x256"],
		["f_Emerald_Ingot","Emerald_Ingot","item",55,[["Emerald_Ingot_Pallet",1]],256,"Craft x256"],
		["f_Gold_Ingot","Gold_Ingot","item",65,[["Gold_Ingot_Pallet",1]],256,"Craft x256"],
		["f_Amethyst_Ingot","Amethyst_Ingot","item",45,[["Amethyst_Ingot_Pallet",1]],256,"Craft x256"]
	],

	["STR_Common_FactoryName_Steel",[4410.48,6755.92,0.15],
		["f_ME_Bucket","ME_Bucket","item",55,[["Steel",15]],1,"Craft x1"],
		["f_ME_Jackhammer","ME_Jackhammer","item",55,[["Steel",15]],1,"Craft x1"],
		["f_Iron_Ingot","Iron_Ingot","item",8,[["Iron_Ore",4]],1,"Craft x1"],
		["f_Coal_Ingot","Coal_Ingot","item",5,[["Coal_Ore",2]],1,"Craft x1"],
		["f_Aluminium_Ingot","Aluminium_Ingot","item",10,[["Aluminium_Ore",6]],1,"Craft x1"],
		["f_Titanium_Ingot","Titanium_Ingot","item",15,[["Titanium_Ore",6]],1,"Craft x1"],
		["f_Sapphire_Ingot","Sapphire_Ingot","item",15,[["Sapphire_Ore",8]],1,"Craft x1"],
		["f_Vivianite_Ingot","Vivianite_Ingot","item",15,[["Vivianite_Ore",6]],1,"Craft x1"],
		["f_Emerald_Ingot","Emerald_Ingot","item",15,[["Emerald_Ore",6]],1,"Craft x1"],
		["f_Gold_Ingot","Gold_Ingot","item",15,[["Gold_Ore",8]],1,"Craft x1"],
		["f_Amethyst_Ingot","Amethyst_Ingot","item",15,[["Amethyst_Ore",4]],1,"Craft x1"],
		["f_Steel","Steel","item",10,[["Iron_Ingot",4],["Coal_Ingot",2]],15,"Craft x15"],
		["f_Aluminium","Aluminium","item",15,[["Aluminium_Ingot",4]],15,"Craft x15"],
		["f_Gold","Gold_Sheet","item",15,[["Gold_Ingot",10]],15,"Craft x15"],
		["f_Titanium","Titanium","item",15,[["Titanium_Ingot",4]],15,"Craft x15"],
		["f_SteelS","Steel","item",10,[["Steel_Pellet",1]],60,"Craft x60"],
		["f_AluminiumS","Aluminium","item",15,[["Aluminium_Pellet",1]],60,"Craft x60"],
		["f_TitaniumS","Titanium","item",15,[["Titanium_Pellet",1]],60,"Craft x60"],
		["f_Steel_Pellet","Steel_Pellet","item",25,[["Steel",60]],1,"Craft x1"],
		["f_Aluminium_Pellet","Aluminium_Pellet","item",30,[["Aluminium",60]],1,"Craft x1"],
		["f_Titanium_Pellet","Titanium_Pellet","item",35,[["Titanium",60]],1,"Craft x1"],
		["f_Iron_Ingot_Pellet","Iron_Ingot_Pellet","item",350,[["Iron_Ingot",256]],1,"Craft x1"],
		["f_Coal_Ingot_Pellet","Coal_Ingot_Pellet","item",900,[["Coal_Ingot",256]],1,"Craft x1"],
		["f_Aluminium_Ingot_Pellet","Aluminium_Ingot_Pellet","item",425,[["Aluminium_Ingot",256]],1,"Craft x1"],
		["f_Titanium_Ingot_Pellet","Titanium_Ingot_Pellet","item",470,[["Titanium_Ingot",256]],1,"Craft x1"],
		["f_Sapphire_Ingot_Pallet","Sapphire_Ingot_Pallet","item",485,[["Sapphire_Ingot",256]],1,"Craft x1"],
		["f_Vivianite_Ingot_Pallet","Vivianite_Ingot_Pallet","item",470,[["Vivianite_Ingot",256]],1,"Craft x1"],
		["f_Emerald_Ingot_Pallet","Emerald_Ingot_Pallet","item",470,[["Emerald_Ingot",256]],1,"Craft x1"],
		["f_Gold_Ingot_Pallet","Gold_Ingot_Pallet","item",500,[["Gold_Ingot",256]],1,"Craft x1"],
		["f_Amethyst_Ingot_Pallet","Amethyst_Ingot_Pallet","item",375,[["Amethyst_Ingot",256]],1,"Craft x1"]
	],

	["STR_Common_FactoryName_Petrol",[4409.1,6678.72,0.168],
		["f_pumpjack","Pumpjack","item",150,[["Steel_Pellet",3]],1,"Craft x1 Pumpjack"],
		["f_Petrol","Petrol","item",55,[["Crude_Oil",1]],3,"Craft x3 Refined Oil"],
		["f_jerrycan_empty","jerrycan_empty","item",10,[["Steel",1]],1,"Craft x1 Empty jerrycan"],
		["f_jerrycan","jerrycan","item",35,[["Petrol",1],["Steel",4]],2,"Craft x4 Jerrycans"],
		["f_jerrycan2","jerrycan","item",35,[["Petrol",1],["jerrycan_empty",4]],4,"Craft x4 Jerrycans"],
		["f_jerrycan_kero","kerosene_jerrycan","item",55,[["Kerosene",1],["Steel",4]],4,"Craft x4 Kerosene jerrycans (for planes)"],
		["f_jerrycan_kero2","kerosene_jerrycan","item",55,[["Kerosene",1],["jerrycan_empty",4]],4,"Craft x4 Kerosene jerrycans (for planes)"],
		["f_Kerosene","Kerosene","item",75,[["Crude_Oil",1]],1,"Craft x1 Kerosene barrel"],
		["f_CanisterOil","CanisterOil","item",5,[["Petrol",1]],20,"Craft x20"]
	],

	["STR_Common_FactoryName_Goods",[6540.34,6670.7,0.168],
		["f_woodpl","woodpl","item",15,[["log",1]],10,"Craft x10"],
		["f_swishers","swishers","item",5,[["log",1]],5,"Craft x15"],
		["f_empty_ziplock","empty_ziplock","item",25,[["Plastic",5]],5,"Craft x5"],
		["f_empty_container","weed_grinded_empty","item",25,[["Plastic",5]],5,"Craft x5"],
		["f_v_lockick","v_lockpick","item",50,[["Steel",10]],1,"Craft x1"],
		["f_zipties","zipties","item",25,[["Plastic",5]],1,"Craft x1"],
		["f_repairwrench","repairwrench","item",50,[["Steel",10]],1,"Craft x1"],
		["f_Rangefinder","Rangefinder","aitem",60,[["Steel",20],["Glass",2]],1,"Craft x1"],
		["f_FD_Adapter","fd_adapter","item",10,[["Steel",1]],1,"Craft x1"],
		["f_FD_Hose","fd_hose","item",5,[["Rubber",1]],3,"Craft x3"],
		["f_Net","net","item",5,[["Plastic",1]],2,"Craft x2"],
		["f_Bucket_Empty","bucket_empty","item",25,[["Plastic",5]],1,"Craft x1"],
		["f_Camper_Light","Camper_Light","item",45,[["Steel",5],["CanisterOil",5]],1,"Craft x1"],
		["f_RocketB","rocket_blue","item",30,[["Gunpowder",5],["Sulphur_Powder",2]],1,"Craft x1"],
		["f_RocketR","rocket_red","item",30,[["Gunpowder",5],["Sulphur_Powder",2]],3,"Craft x3"],
		["f_RocketG","rocket_green","item",30,[["Gunpowder",5],["Sulphur_Powder",2]],3,"Craft x3"],
		["f_RocketY","rocket_yellow","item",30,[["Gunpowder",5],["Sulphur_Powder",2]],3,"Craft x3"],
		["f_bandage","med_bandage","item",10,[["Polyester",1]],10,"Craft x10"],
		["f_icepack","med_icepack","item",15,[["Plastic",3]],5,"Craft x5"],
		["f_painkillers","med_painkillers","item",15,[["coca",3],["sugarcane",3]],3,"Craft x3"],
        ["f_antistress","med_antistress","item",15,[["coca",3],["sugarcane",3]],3,"Craft x3"],
		["f_splint","med_splint","item",25,[["Plastic",3]],5,"Craft x5"],
		["f_bloodbagempty","medS_bloodbagempty","item",25,[["Plastic",10],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_autograftkit","med_autograftkit","item",25,[["Plastic",10],["Steel",10],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_med_narcan","med_narcan","item",25,[["coca",50],["sugarcane",50],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_cast","med_cast","item",25,[["glass_fibre",100],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_endotracheal","med_endotracheal","item",25,[["Plastic",20],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_kit","med_kit","item",25,[["Steel",10],["Plastic",15],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_oxygenmask","med_oxygenmask","item",25,[["Plastic",10],["blueprint_fifr",1]],50,"Reserved to FIFR"],
		["f_lifealert","life_alert","item",55,[["Plastic",20]],1,"Craft x1"],
		["f_scale","scale","item",50,[["Steel",10]],1,"Craft x1"],
		["f_fan","fan","item",55,[["Steel",5],["Plastic",10]],1,"Craft x1"],
		["f_grinder","grinder","item",55,[["Steel",7],["Plastic",7]],1,"Craft x1"],
		["f_planter","planter","item",50,[["Steel",10]],1,"Craft x1"],
		["f_lamp_200w","lamp_200w","item",60,[["Steel",10],["Plastic",10]],1,"Craft x1"],
		["f_lamp_500w","lamp_500w","item",60,[["Steel",11],["Plastic",11]],1,"Craft x1"],
		["f_lamp_1000w","lamp_1000w","item",60,[["Steel",12],["Plastic",12]],1,"Craft x1"],
		["f_pavilion","pavilion","item",45,[["Steel",5],["Plastic",5]],1,"Craft x1"],
		["f_workbench","workbench","item",45,[["woodpl",5]],1,"Craft x1"],
		["f_cocaine_barrel","cocaine_barrel","item",45,[["Plastic",10]],1,"Craft x1"],
		["f_weed_rack","weed_rack","item",55,[["aluminium",8]],1,"Craft x1"],
		["f_Pickaxe","A3PL_Pickaxe","weapon",55,[["Steel",34],["log",1]],1,"Craft x1"],
		["f_Sovel","A3PL_Shovel","weapon",55,[["Steel",34],["log",1]],1,"Craft x1"],
		["f_tagmeat","tag_meat","item",10,[["Plastic",3],["woodpl",1]],1,"Craft x1"]
	],

	["STR_Common_FactoryName_Foods",[8968.17,6391.78,0.168],
		["f_candycane","candycane","item",5,[["sugarcane",1]],1,"Craft x1"],
		["f_applejuice","applejuice","item",20,[["apple",2],["sugarcane",2],["Aluminium_Ingot",1]],3,"Craft x3"],
		["f_carrotjuice","carrotjuice","item",10,[["Plastic",1],["sugarcane",2],["carrot",4]],2,"Craft x2"],
		["f_soup","soup","item",30,[["Plastic",1],["carrot",2],["lettuce",2],["wheat",6],["corn",2]],1,"Craft x1"],
		["f_cola","coke","item",20,[["coca",2],["sugarcane",2],["Aluminium_Ingot",1]],3,"Craft x3"],
		["f_Coffee_Cup_Large","coffee_cup_large","item",25,[["coca",6],["plastic",4]],2,"Craft x2"],
		["f_Coffee_Cup_Medium","coffee_cup_medium","item",20,[["coca",5],["plastic",2]],2,"Craft x2"],
		["f_Coffee_Cup_Small","coffee_cup_small","item",20,[["coca",4],["plastic",1]],2,"Craft x2"],
		["f_hoagie","hoagie","item",30,[["bread",1],["Lettuce",3],["meat_firstprice_tranched",1]],2,"Craft x3"],
		["f_donut_plain","donut_plain","item",5,[["wheat",10]],2,"Craft x2"],
		["f_donut_choc","donut_choc","item",10,[["wheat",10],["coca",3]],2,"Craft x2"],
		["f_donut_pink","donut_pink","item",10,[["wheat",10],["sugarcane",8]],2,"Craft x2"],
		["f_sandwich_hamcheese","sandwich_hamcheese","item",30,[["bread",1],["Lettuce",3],["meat_pork_tranched",1]],2,"Craft x2"],
		["f_sandwich_veggie","sandwich_veggie","item",10,[["bread",1],["Lettuce",4]],2,"Craft x2"],
		["f_popcornbucket","popcornbucket","item",10,[["Corn",5]],1,"Craft x1"],
		["f_burgerbun","burger_bun","item",10,[["wheat",20]],2,"Craft x2"],
		["f_burger_raw","burger_raw","item",15,[["bucket_full",1]],10,"Craft x10"],
		["f_tacoshell","tacoshell","item",10,[["Corn",5]],5,"Craft x5"],
		["f_salad","salad","item",5,[["Lettuce",2]],5,"Craft x5"],
		["f_fish","fish_raw","item",15,[["bucket_full",1]],10,"Craft x10"],
		["f_pizzabites","pizzabites","item",25,[["meat_sheep_tag",1],["bread",1]],4,"Craft x4"],
		["f_soupcoup","soupcup","item",30,[["meat_sheep_tag",2],["corn",10]],3,"Craft x3"],
		["f_cookies","cookies","item",10,[["coca",2],["sugarcane",2],["wheat",15]],2,"Craft x2"],
		["f_bread","bread","item",15,[["wheat",30]],2,"Craft x2"],
		["f_applecookies","applecookies","item",15,[["coca",2],["sugarcane",2],["wheat",15],["apple",2]],5,"Craft x5"],
		["f_cereal","cereal","item",20,[["corn",15],["wheat",20]],8,"Craft x8"],
		["f_lamington","lamington","item",10,[["sugarcane",3],["bread",1]],2,"Craft x2"],
		["f_sausages","sausages","item",30,[["meat_agneau_tranched",1]],2,"Craft x2"],
		["f_burger_full_cooked","burger_full_cooked","item",30,[["salad",1],["burger_bun",2],["burger_cooked",1]],1,"Craft x1"],
		["f_taco_cooked","taco_cooked","item",25,[["salad",3],["tacoshell",1],["fish_cooked",1]],1,"Craft x1"],
		["f_meatpie","meatpie","item",55,[["meat_pork_tranched",1],["meat_beef_tranched",2],["meat_agneau_tranched",1],["bread",1]],3,"Craft x3"],
		["f_meat_firstprice_tranched","meat_firstprice_tranched","item",20,[["meat_sheep_tag",1]],10,"Craft x10"],
		["f_meat_pork_tranched","meat_pork_tranched","item",20,[["meat_boar_tag",1]],5,"Craft x5"],
		["f_meat_agneau_tranched","meat_agneau_tranched","item",20,[["meat_goat_tag",1]],5,"Craft x5"],
		["f_meat_beef_tranched","meat_beef_tranched","item",20,[["meat_cow_tag",1]],5,"Craft x5"]
	],

	["STR_Common_FactoryName_IllegalWeapons",[6540.34,6670.7,0.168],
		["f_Glock17","A3FL_Glock17","weapon",350,[["Steel",242]],1,"Craft x1 Glock 17"],
		["f_Glock17_Mag","A3FL_Glock17_Mag","magazine",90,[["Steel",15],["Gunpowder",16]],5,"Craft x5 17Rnd 9mm Mags; For: Glock17 & Glock17 SEAR"],
		["f_Glock17S","A3FL_Glock17S","weapon",350,[["Steel",242],["Plastic",15]],1,"Craft x1 Glock 17 SEAR"],
		["f_Glock26","A3FL_Glock26","weapon",1200,[["Steel",257]],1,"Craft x1 Glock 26"],
		["f_Glock26_Mag","A3FL_Glock26_Mag","magazine",90,[["Steel",26],["Gunpowder",26]],5,"Craft x5 10Rnd 9mm Mags; For: Glock26"],
		["f_P226","A3PL_P226","weapon",1200,[["Steel",185]],1,"Craft x1 SIG P226"],
		["f_P226_Mag","A3PL_P226_Mag","magazine",90,[["Steel",10],["Gunpowder",11]],5,"Craft x5 15Rnd 9x19mm Mags; For: SIG P226"],
		["f_P227","A3FL_P227","weapon",1500,[["Steel",202]],1,"Craft x1 SIG P227"],
		["f_P227_Mag","A3FL_P227_Mag","magazine",90,[["Steel",13],["Gunpowder",13]],5,"Craft x5 12Rnd .45 Mags; For: SIG P227"],
		["f_FNX45","A3FL_FNX45","weapon",350,[["Steel",247]],1,"Craft x1 FN FNX .45"],
		["f_FNX45_Mag","A3FL_FNX45_Mag","magazine",90,[["Steel",17],["Gunpowder",18]],5,"Craft x5 15Rnd .45 Mags; For: FN FNX"],
		["f_Beretta92","A3FL_Beretta92","weapon",350,[["Steel",250]],1,"Craft x1 Beretta 92"],
		["f_Beretta92_Mag","A3FL_Beretta92_Mag","magazine",90,[["Steel",10],["Gunpowder",10]],5,"Craft x5 15Rnd 9x19mm Mags; For: Beretta 92"],
		["f_DesertEagle","A3FL_DesertEagle","weapon",2100,[["Steel",300]],1,"Craft x1 Desert Eagle"],
		["f_DesertEagleGold","A3FL_DesertEagleGold","weapon",2400,[["Steel",300],["Gold_sheet",5]],1,"Craft x1 Golden Desert Eagle"],
		["f_DesertEagle_Mag","A3FL_DesertEagle_Mag","magazine",90,[["Steel",27],["Gunpowder",27]],5,"Craft x5 7Rnd .50 Mags; For: Desert Eagle"],
		["f_Python","A3FL_Python","weapon",350,[["Steel",277]],1,"Craft x1 Colt Python .357"],
		["f_PythonGold","A3FL_PythonGold","weapon",2100,[["Steel",277],["Gold_sheet",5]],1,"Craft x1 Golden Colt Python .357"],
		["f_Python_Mag","A3FL_Python_Mag","magazine",90,[["Steel",26],["Gunpowder",26]],5,"Craft x5 6Rnd .357 Magnum Mags; For: Colt Python"],
		["f_30rnds_mag","30Rnd_9x21_Mag","magazine",90,[["Steel",13],["Gunpowder",13]],1,"Craft x1 Mag. 30 balles 9mm;"],
		["f_optic_ACO_grn_smg","optic_ACO_grn_smg","aitem",120,[["Steel",11],["Glass",16]],1,"Craft x1 ACO SMG; For all SMGs"],
		["f_optic_ACO_smg","optic_ACO_smg","aitem",120,[["Steel",11],["Glass",16]],1,"Craft x1 ACO Sight; For all assault rifles and SMGs"],
		["f_optic_Holosight_smg_blk_F","optic_Holosight_smg_blk_F","aitem",120,[["Steel",11],["Glass",16]],1,"Craft x1 Holosight Mk17; For all SMGs"]
	],

	["STR_Common_FactoryName_LegalWeapons",[6540.34,6670.7,0.168],
		["f_P07","hgun_P07_F","weapon",150,[["Steel",154]],1,"Craft x1 P07 9mm"],
		["f_P07_khk","hgun_P07_khk_F","weapon",150,[["Steel",154]],1,"Craft x1 P07 Kaki 9mm"],
		["f_P07_blk","hgun_P07_blk_F","weapon",150,[["Steel",154]],1,"Craft x1 P07 Noir 9mm"],
		["f_Rook40","hgun_Rook40_F","weapon",150,[["Steel",185]],1,"Craft x1 Rook-40 9mm"],
		["f_16Rnd_9x21_Mag","16Rnd_9x21_Mag","magazine",90,[["Steel",10],["Gunpowder",10]],5,"Craft x5 Mag. 16 balles 9mm; For: P07/Rook-40"],
		["f_Glock17_legal","A3FL_Glock17","weapon",250,[["Steel",210]],1,"Craft x1 Glock 17"],
		["f_Glock17_legal_Mag","A3FL_Glock17_Mag","magazine",90,[["Steel",20],["Gunpowder",15]],5,"Craft x5 17Rnd 9mm Glock17 Mag"],
		["f_Pistol_heavy_01","hgun_Pistol_heavy_01_F","weapon",250,[["Steel",190]],1,"Craft x1 4-Five .45 ACP"],
		["f_11Rnd_45ACP_Mag","11Rnd_45ACP_Mag","magazine",90,[["Steel",10],["Gunpowder",10]],5,"Craft x5 Mag. 11 balles .45 ACP; For: 4-five ACP"],
		["f_ACPC2","hgun_ACPC2_F","weapon",250,[["Steel",190]],1,"Craft x1 ACP-C2 .45 ACP Pistol"],
		["f_9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","magazine",90,[["Steel",8],["Gunpowder",9]],5,"Craft x5 Mag. 9 balles .45 ACP; For: ACP-C2"],
		["f_Pistol_01","hgun_Pistol_01_F","weapon",250,[["Steel",100]],1,"Craft x1 PM 9mm"],
		["f_10Rnd_9x21_Mag","10Rnd_9x21_Mag","magazine",90,[["Steel",6],["Gunpowder",5]],5,"Craft x5 Mag. 10 balles 9mm; For: PM"],
		["f_Pistol_heavy_02","hgun_Pistol_heavy_02_F","weapon",250,[["Steel",200]],1,"Craft x1 Zubr .45 ACP"],
		["f_6Rnd_45ACP_Mag","6Rnd_45ACP_Cylinder","magazine",90,[["Steel",8],["Gunpowder",8]],5,"Craft x5 6 bullets cylinder .45 ACP; For: Zubr"],
		["f_Beretta92","A3FL_Beretta92","weapon",250,[["Steel",250]],1,"Craft x1 Beretta 92"],
		["f_Beretta92_Mag","A3FL_Beretta92_Mag","magazine",90,[["Steel",10],["Gunpowder",9]],5,"Craft x5 15Rnd 9x19mm; For: Beretta"],
		["f_acc_flashlight_pistol","acc_flashlight_pistol","aitem",120,[["Steel",30]],1,"Craft x1 Pistol flashlight; For most pistols"],
		["f_Taser2","A3PL_Taser2","weapon",250,[["Plastic",130]],1,"Craft x1 Taser"],
		["f_Taser2_Mag","A3PL_Taser2_Mag","magazine",90,[["Plastic",10]],5,"Craft x5 Taser Magazine"],
		["f_Pistol_Signal_F","hgun_Pistol_Signal_F","weapon",250,[["Steel",50]],1,"Craft x1 Signal pistol"],
		["f_6Rnd_GreenSignal_F","6Rnd_GreenSignal_F","magazine",90,[["Steel",5],["Gunpowder",5]],5,"Craft x5 6 Green signal cylinder"],
		["f_6Rnd_RedSignal_F","6Rnd_RedSignal_F","magazine",90,[["Steel",5],["Gunpowder",5]],5,"Craft x5 6 Red signal cylinder"],
		["f_Huntingrifle","EC_Huntingrifle","weapon",300,[["Steel",400],["titanium",20]],1,"Craft x1 Savage Scout .308"],
		["f_10rnd_308","EC_10rnd_308","magazine",120,[["Steel",44],["Gunpowder",88]],10,"Craft x10 10Rnd .308 Mag"],
		["f_MP7_legal","A3FL_MP7","weapon",300,[["Steel",355],["titanium",20]],1,"Craft x1 HK MP7"],
		["f_MP7_legal_Mag","A3FL_MP7_Mag","magazine",120,[["Steel",90],["Gunpowder",130],["titanium",10]],15,"Craft x15 40Rnd 4.6mm Mag"],
		["f_MP5K_legal","A3FL_MP5K","weapon",300,[["Steel",435],["titanium",20]],1,"Craft x1 HK MP5K"],
		["f_MP5K_legal_Mag","A3FL_MP5K_Mag","magazine",120,[["Steel",100],["Gunpowder",135],["titanium",10]],15,"Craft x15 30Rnd 9mm MP5K Mag"],
		["f_Mossberg","A3FL_Mossberg_590K","weapon",300,[["Steel",500],["titanium",20]],1,"Craft x1 Mossberg 590K"],
		["f_Mossberg_Mag","A3FL_Mossberg_590K_8Rnd_buck","magazine",120,[["Steel",115],["Gunpowder",140],["titanium",10]],15,"Craft x15 12 Gauge 7+1 Rnd Buckshot"],
		["f_MP9","EC_MP9","weapon",300,[["Steel",435],["titanium",20]],1,"Craft x1 BT MP9"],
		["f_MP9_Mag","EC_MP9_Mag","magazine",120,[["Steel",100],["Gunpowder",135],["titanium",10]],15,"Craft x15 30Rnd 9mm MP9 Mag"],
		["f_Uzi","A3FL_Uzi","weapon",280,[["Steel",320],["titanium",15]],1,"Craft x1 Micro Uzi"],
		["f_Uzi_Mag","A3FL_Uzi_Mag","magazine",120,[["Steel",80],["Gunpowder",110],["titanium",5]],15,"Craft x15 20Rnd 9mm Uzi Mag"],
		["f_CZ550","A3PL_CZ550","weapon",300,[["Steel",400],["titanium",20]],1,"Craft x1 CZ550"],
		["f_5rnd_3006","A3PL_5rnd_3006","magazine",120,[["Steel",44],["Gunpowder",88]],10,"Craft x10 5Rnd 3006 Mag"],
		["f_SMG_01_F","SMG_01_F","weapon",300,[["Steel",435],["titanium",20]],1,"Craft x1 Kriss Vector"],
		["f_30Rnd_45ACP_Mag_SMG_01","30Rnd_45ACP_Mag_SMG_01","magazine",120,[["Steel",80],["Gunpowder",110],["titanium",5]],15,"Craft x15 45 ACP Mag"]
	],

	["STR_Common_FactoryName_FactionWeapons",[6540.34,6670.7,0.168],
		["f_flash","FYD_Flash","magazine",90,[["Steel",40],["Plastic",40],["Gunpowder",40],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_Shield","A3FL_Shield","weapon",120,[["Steel",200],["Plastic",10],["fibreglass",10],["titanium",50],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_PepperSpray","A3FL_PepperSpray","weapon",600,[["Steel",150],["blueprint_fisd",1]],3,"Reserved to FISD"],
		["f_PepperSprayMag","A3FL_PepperSpray_Mag","magazine",90,[["Plastic",75],["blueprint_fisd",1]],50,"Reserved to FISD"],
		["f_Taser","A3PL_Taser","weapon",100,[["Plastic",950],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_TaserMag","A3PL_TaserMag","magazine",90,[["Plastic",100],["blueprinteq_fisd",1]],50,"Reserved to FISD"],
		["f_Python","A3FL_Python","weapon",150,[["Steel",1250],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_Python_Mag","A3FL_Python_Mag","magazine",90,[["Steel",120],["Gunpowder",142],["blueprinteq_fisd",1]],25,"Reserved to FISD"],
		["f_Glock26","A3FL_Glock26","weapon",150,[["Steel",1250],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_Glock26_Mag","A3FL_Glock26_Mag","magazine",90,[["Steel",120],["Gunpowder",142],["blueprinteq_fisd",1]],25,"Reserved to FISD"],
		["f_Glock17","A3FL_Glock17","weapon",150,[["Steel",1200],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_Glock17_Mag","A3FL_Glock17_Mag","magazine",90,[["Steel",60],["Gunpowder",100],["blueprinteq_fisd",1]],17,"Reserved to FISD"],
		["f_M4","A3FL_M4","weapon",300,[["Steel",945],["titanium",44],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_M16","A3PL_M16","weapon",300,[["Steel",900],["titanium",40],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_MK18","A3FL_MK18","weapon",300,[["Steel",1000],["titanium",50],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_M16_Mag","A3PL_M16_Mag","magazine",120,[["Steel",87],["Gunpowder",130],["titanium",20],["blueprinteq_fisd",1]],20,"Reserved to FISD"],
		["f_ACR","A3FL_ACR","weapon",300,[["Steel",1050],["titanium",55],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_ACR_Mag","A3FL_ACR_Mag","magazine",120,[["Steel",82],["Gunpowder",121],["titanium",20],["blueprinteq_fisd",1]],20,"Reserved to FISD"],
		["f_MP7","A3FL_MP7","weapon",250,[["Steel",1110],["titanium",50],["blueprint_fisd",1]],3,"Reserved to FISD"],
		["f_MP7_Mag","A3FL_MP7_Mag","magazine",120,[["Steel",86],["Gunpowder",122],["titanium",10],["blueprinteq_fisd",1]],20,"Reserved to FISD"],
		["f_MP7_T_Mag","A3FL_MP7_T_Mag","magazine",50,[["Plastic",115],["blueprinteq_fisd",1]],30,"Reserved to FISD"],
		["f_UMP","A3FL_UMP","weapon",250,[["Steel",1110],["titanium",50],["blueprint_fisd",1]],3,"Reserved to FISD"],
		["f_UMP_Mag","A3FL_UMP_Mag","magazine",120,[["Steel",86],["Gunpowder",122],["titanium",10],["blueprinteq_fisd",1]],20,"Reserved to FISD"],
		["f_UMP_T_Mag","A3FL_UMP_T_Mag","magazine",50,[["Plastic",115],["blueprinteq_fisd",1]],30,"Reserved to FISD"],
		["f_M870","A3FL_M870","weapon",500,[["Steel",400],["titanium",20],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_M870_Buck","A3FL_M870_Buck","magazine",120,[["Steel",44],["Gunpowder",88],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_M870_Slug","A3FL_M870_Slug","magazine",120,[["Steel",44],["Gunpowder",88],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_M870_Beanbag","A3FL_M870_Beanbag","magazine",120,[["Steel",44],["Gunpowder",88],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_M870_Breach","A3FL_M870_Breach","magazine",120,[["Steel",60],["Gunpowder",89],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_Benelli","A3FL_Benelli","weapon",200,[["Steel",400],["titanium",25],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Benelli_Buck","A3FL_Benelli_Buck","magazine",120,[["Steel",44],["Gunpowder",88],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_Benelli_Slug","A3FL_Benelli_Slug","magazine",120,[["Steel",44],["Gunpowder",88],["blueprinteq_fisd",1]],10,"Reserved to FISD"],
		["f_Benelli_T_Mag","A3FL_Benelli_T_Mag","magazine",90,[["Plastic",115],["blueprinteq_fisd",1]],30,"Reserved to FISD"],
		["f_Glock17_T","A3FL_Glock17_T","weapon",150,[["Plastic",500],["blueprint_fisd",1]],5,"Reserved to FISD"],
		["f_Glock17_T_Mag","A3FL_Glock17_T_Mag","magazine",90,[["Plastic",53],["blueprinteq_fisd",1]],30,"Reserved to FISD"],

		["f_M16T","A3PL_M16_Training","weapon",150,[["Plastic",500],["blueprint_fisd",1]],2,"Reserved to FISD"],
		["f_M16_Training_Mag","A3PL_M16_T_Mag","magazine",90,[["Plastic",115],["blueprinteq_fisd",1]],30,"Reserved to FISD"],
		["f_optic_aco_grn_smg","optic_aco_grn_smg","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_aco_smg","optic_aco_smg","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_RMR_Tall","optic_RMR_Tall","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_RMR","optic_RMR","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_CompM5","optic_CompM5","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_MRCO","optic_MRCO","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_Hamr","optic_Hamr","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_ERCO","optic_ERCO_blk_F","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_Holosight_blk_F","optic_Holosight_blk_F","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_acc_flashlight","acc_flashlight","aitem",120,[["Steel",145],["fibreglass",4],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_flashlight_x300","flashlight_x300","aitem",120,[["Steel",145],["fibreglass",4],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_acc_flashlight_pistol","acc_flashlight_pistol","aitem",120,[["Steel",142],["fibreglass",4],["blueprinteq_fisd",1]],5,"Reserved to FISD"],
		["f_optic_Holosight_smg_blk_F","optic_Holosight_smg_blk_F","aitem",120,[["Steel",88],["fibreglass",13],["blueprinteq_fisd",1]],5,"Reserved to FISD"]
	],

	["STR_Common_FactoryName_Boats",[4898.23,5060.04,13],
		["f_Rebreather","V_RebreatherB","vest",60,[["Steel",20],["Plastic",10]],1,""],
		["f_jetski","C_Scooter_Transport_01_F","car",350,[["Steel_Pellet",2],["Aluminium_Pellet",2]],1,""],
		["f_Motorboat","A3PL_Motorboat","car",425,[["Steel_Pellet",10],["Aluminium_Pellet",10],["Windows",3]],1,""],
		["f_waterSkis","A3PL_Ski_Base","car",450,[["Aluminium_Pellet",1]],1,""],
		["f_RHIB","A3PL_RHIB","car",350,[["Steel_Pellet",6],["Aluminium_Pellet",5]],1,""],
		["f_LCM","A3FL_LCM","car",375,[["Steel_Pellet",15],["Aluminium_Pellet",15],["Plastic",2]],1,""],
		["f_LuxuryYatch","A3PL_Yacht","car",1000,[["Steel_Pellet",100],["Aluminium_Pellet",100],["Titanium_Pellet",100],["Windows",76]],1,""],
		["f_RBM","A3PL_RBM","car",375,[["Steel_Pellet",20],["Aluminium_Pellet",20],["Titanium_Pellet",2],["Windows",5],["blueprint_fisd",1]],1,""]
	],

	["STR_Common_FactoryName_Aircrafts",[2907.86,5260.62,0.4],
		["f_PalletLifter","A3FL_PalletLifter","plane",350,[["Aluminium_Pellet",5],["Steel_Pellet",5]],1,""],
		["f_TransportContainer","A3FL_TransportContainer","plane",425,[["Aluminium_Pellet",10],["Steel_Pellet",10]],1,""],
		["f_Heli_Light","A3FL_M_900_Base_F","plane",485,[["Aluminium_Pellet",23],["Steel_Pellet",28],["Titanium_Pellet",12],["Windows",7]],1,""],
		["f_AS350","A3FL_AS350_CIV","plane",500,[["Aluminium_Pellet",25],["Windows",10],["Titanium_Pellet",16],["Steel_Pellet",30]],1,""],
		["f_Heli","Heli_Medium01_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28]],1,""],
		["f_Military_Heli","Heli_Medium01_Military_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28]],1,""],
		["f_Veteran_Heli","Heli_Medium01_Veteran_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28]],1,""],
		["f_Luxury_Heli","Heli_Medium01_Luxury_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28]],1,""],
		["f_Cessna172","A3PL_Cessna172","plane",950,[["Aluminium_Pellet",35],["Steel_Pellet",32],["Titanium_Pellet",23],["Windows",7]],1,""],
		["f_Goose","A3PL_Goose_Base","plane",1000,[["Aluminium_Pellet",38],["Steel_Pellet",35],["Titanium_Pellet",39],["Windows",14]],1,""],
		["f_SteerableParachute","B_Parachute","backpack",60,[["Polyester",10],["Steel",2],["Plastic",5]],1,""],
		["f_Jayhawk_FISD","A3PL_Jayhawk","plane",600,[["Aluminium_Pellet",25],["Windows",10],["Titanium_Pellet",20],["Steel_Pellet",30],["blueprint_fisd",1]],1,"Hélicoptère Reserved to FISD"],
		["f_AS_365fisd","A3FL_AS_365","plane",600,[["Aluminium_Pellet",25],["Windows",10],["Titanium_Pellet",18],["Steel_Pellet",30],["blueprint_fisd",1]],1,"Hélicoptère Reserved to FISD"],
		["f_AS_365fifr","A3FL_AS_365","plane",600,[["Aluminium_Pellet",25],["Windows",10],["Titanium_Pellet",18],["Steel_Pellet",30],["blueprint_fifr",1]],1,"Hélicoptère réservé au FIFR"],
		["f_Sheriff_Heli","Heli_Medium01_Sheriff_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28],["blueprint_fisd",1]],1,"Hélicoptère Reserved to FISD"],
		["f_Medic_Heli","Heli_Medium01_Medic_H","plane",500,[["Aluminium_Pellet",24],["Windows",10],["Titanium_Pellet",15],["Steel_Pellet",28],["blueprint_fifr",1]],1,"Hélicoptère réservé au FIFR"]
	],

	["STR_Common_FactoryName_Vehicles",[3000.25,5352.92,0.4],
		["f_Windows","Windows","item",5,[["Glass",1]],2,"Craft x2 Fenêtres"],
		["f_Tyres","Tyres","item",5,[["Rubber",1]],2,"Craft x2 Roues"],
		["f_scooter","K_Scooter_DarkBlue","car",900,[["Aluminium_Pellet",2]],1,""],
		["f_C_Kart_01_F","C_Kart_01_F","car",900,[["Steel_Pellet",3]],1,""],
		["f_quad","C_Quadbike_01_F","car",900,[["Steel_Pellet",1],["Aluminium_Pellet",1]],1,""],
		["f_Smart_Car","A3FL_Smart_Car","car",900,[["Steel_Pellet",3],["Aluminium_Pellet",3],["Windows",2],["Tyres",4]],1,""],
		["f_CVPI_rust","A3PL_CVPI_Rusty","car",900,[["Steel_Pellet",2],["Aluminium_Pellet",2],["Windows",4],["Tyres",4]],1,""],
		["f_CVPI","A3PL_CVPI","car",900,[["Steel_Pellet",3],["Aluminium_Pellet",2],["Windows",4],["Tyres",4]],1,""],
		["f_CVPI_Taxi","A3PL_CVPI_Taxi","car",900,[["Steel_Pellet",3],["Aluminium_Pellet",2],["Windows",4],["Tyres",4]],1,""],
		["f_Taurus","A3FL_Taurus","car",350,[["Steel_Pellet",7],["Aluminium_Pellet",7],["Windows",4],["Tyres",4]],1,""],
		["f_Focus","A3FL_Focus","car",425,[["Steel_Pellet",13],["Aluminium_Pellet",8],["Windows",4],["Tyres",4]],1,""],
		["f_Fuel_van","A3PL_Fuel_Van","car",375,[["Steel_Pellet",15],["Aluminium_Pellet",10],["Windows",2],["Tyres",6]],1,""],
		["f_150","A3PL_F150","car",375,[["Steel_Pellet",15],["Aluminium_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_150_lb","A3PL_F150_Marker","car",375,[["Steel_Pellet",16],["Aluminium_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_F450","A3FL_F450","car",375,[["Steel_Pellet",18],["Aluminium_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_E350","A3FL_E350","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Windows",2],["Tyres",4]],1,""],
		["f_E350_ML","A3FL_E350_ML","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",12],["Windows",2],["Tyres",4]],1,""],
		["f_E350_P","A3FL_E350_P","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",12],["Windows",2],["Tyres",4]],1,""],
		["f_Explorer19","EC_Explorer19","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",14],["Windows",4],["Tyres",4]],1,""],
		["f_DodgeRam","EC_DodgeRam_Lowered","car",450,[["Steel_Pellet",19],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_18F150","A3FL_F150","car",450,[["Steel_Pellet",19],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_18F150_ML","A3FL_F150_ML","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
        ["f_Explorer_Platinum_20","A3FL_Explorer_Platinum_20","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",4],["Tyres",4]],1,""],
		["f_Mustang","A3PL_Mustang","car",470,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_Mustang15","A3FL_Mustang15","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",20],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_Ram","A3PL_Ram","car",900,[["Steel_Pellet",3],["Aluminium_Pellet",3],["Windows",2],["Tyres",4]],1,""],
		["f_Ram_ML","A3PL_Ram_ML","car",900,[["Steel_Pellet",4],["Aluminium_Pellet",3],["Windows",2],["Tyres",4]],1,""],
		["f_69Charger","A3PL_Charger69","car",425,[["Steel_Pellet",11],["Aluminium_Pellet",6],["Windows",2],["Tyres",4]],1,""],
		["f_Charger","A3PL_Charger","car",375,[["Steel_Pellet",18],["Aluminium_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_Charger_Hellcat_20","EC_Charger_Hellcat_20","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_Challenger_Hellcat","A3PL_Challenger_Hellcat","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",2],["Tyres",4]],1,""],
		["f_Tahoe","A3PL_Tahoe","car",425,[["Steel_Pellet",9],["Aluminium_Pellet",7],["Windows",4],["Tyres",4]],1,""],
		["f_Suburban","A3FL_Suburban","car",425,[["Steel_Pellet",10],["Aluminium_Pellet",8],["Windows",4],["Tyres",4]],1,""],
		["f_Camaro","A3PL_Camaro","car",425,[["Steel_Pellet",12],["Aluminium_Pellet",7],["Windows",2],["Tyres",4]],1,""],
		["f_Silverado","A3PL_Silverado","car",375,[["Aluminium_Pellet",14],["Steel_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_Silverado_ML","A3PL_Silverado_ML","car",375,[["Aluminium_Pellet",15],["Steel_Pellet",12],["Windows",4],["Tyres",4]],1,""],
		["f_Tahoe18","A3FL_Tahoe","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",13],["Titanium_Pellet",2],["Windows",4],["Tyres",4]],1,""],
		["f_ZR1","A3PL_VetteZR1","car",470,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_CamaroZL1","A3FL_CamaroZL1","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",20],["Titanium_Pellet",7],["Windows",2],["Tyres",8]],1,""],
		["f_1100R","A3PL_1100R","car",425,[["Steel_Pellet",8],["Aluminium_Pellet",6],["Titanium_Pellet",2],["Tyres",2]],1,""],
		["f_BMW_M3","A3PL_BMW_M3","car",425,[["Steel_Pellet",15],["Aluminium_Pellet",8],["Windows",4],["Tyres",4]],1,""],
		["f_BMW_X5","A3PL_BMW_X5","car",375,[["Steel_Pellet",18],["Aluminium_Pellet",9],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_BMW_M6","A3FL_BMW_M6","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",15],["Titanium_Pellet",4],["Windows",2],["Tyres",4]],1,""],
		["f_BMW_M6_Tuned","A3FL_BMW_M6_Tuned","car",470,[["Steel_Pellet",16],["Aluminium_Pellet",15],["Titanium_Pellet",4],["Windows",2],["Tyres",4]],1,""],
		["f_G65","A3FL_G65","car",450,[["Steel_Pellet",15],["Aluminium_Pellet",15],["Titanium_Pellet",3],["Windows",4],["Tyres",4]],1,""],
		["f_Mercedes_Benz_AMG_C63","A3FL_Mercedes_Benz_AMG_C63","car",470,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",4],["Tyres",4]],1,""],
		["f_370z","A3FL_370z","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",14],["Titanium_Pellet",4],["Windows",2],["Tyres",4]],1,""],
		["f_Nissan_GTR","A3FL_Nissan_GTR","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",15],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_Nissan_GTR_LW","A3FL_Nissan_GTR_LW","car",470,[["Steel_Pellet",16],["Aluminium_Pellet",15],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_Fatboy","A3PL_Fatboy","car",350,[["Steel_Pellet",6],["Aluminium_Pellet",3],["Titanium_Pellet",2],["Tyres",2]],1,""],
		["f_Knucklehead","A3PL_Knucklehead","car",425,[["Steel_Pellet",8],["Aluminium_Pellet",4],["Titanium_Pellet",2],["Tyres",2]],1,""],
		["f_Escalade","A3FL_Escalade","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_ElDorado","A3FL_ElDorado","car",450,[["Steel_Pellet",15],["Aluminium_Pellet",16],["Titanium_Pellet",3],["Tyres",4]],1,""],
		["f_Gallardo","A3PL_Gallardo","car",485,[["Steel_Pellet",15],["Aluminium_Pellet",20],["Titanium_Pellet",13],["Windows",2],["Tyres",4]],1,""],
        ["f_Performante","EC_Performante","car",600,[["Steel_Pellet",30],["Aluminium_Pellet",35],["Titanium_Pellet",25],["Windows",2],["Tyres",4]],1,""],
		["f_Kx","A3PL_Kx","car",900,[["Steel_Pellet",4],["Aluminium_Pellet",2],["Tyres",2]],1,""],
		["f_HondaCRX","A3PL_CRX","car",350,[["Steel_Pellet",4],["Aluminium_Pellet",4],["Windows",4],["Tyres",4]],1,""],
		["f_Wrangler","A3PL_Wrangler","car",350,[["Steel_Pellet",8],["Aluminium_Pellet",4],["Windows",4],["Tyres",4]],1,""],
		["f_Rover","A3PL_Rover","car",450,[["Steel_Pellet",19],["Aluminium_Pellet",14],["Windows",4],["Tyres",4]],1,""],
		["f_Yukon","A3FL_Yukon","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4]],1,""],
		["f_supra","A3FL_Supra","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_RS7","A3FL_RS7","car",470,[["Steel_Pellet",15],["Aluminium_Pellet",17],["Titanium_Pellet",4],["Windows",2],["Tyres",4]],1,""],
		["f_911GT2","A3PL_911GT2","car",485,[["Steel_Pellet",15],["Aluminium_Pellet",20],["Titanium_Pellet",10],["Windows",2],["Tyres",4]],1,""],
		["f_Dawn","A3FL_Dawn","car",500,[["Steel_Pellet",15],["Aluminium_Pellet",25],["Titanium_Pellet",15],["Tyres",4]],1,""],
		["f_F12","A3FL_F12","car",600,[["Steel_Pellet",26],["Aluminium_Pellet",32],["Titanium_Pellet",21],["Windows",2],["Tyres",4]],1,""],
		["f_p362","A3PL_P362","car",425,[["Steel_Pellet",14],["Aluminium_Pellet",7],["Windows",2],["Tyres",10]],1,""],
		["f_Tow_Truck","A3PL_P362_TowTruck","car",375,[["Steel_Pellet",15],["Aluminium_Pellet",15],["Windows",2],["Tyres",10]],1,""],
		["f_t440_Tow_Truck","A3FL_T440_Tow_Truck","car",375,[["Steel_Pellet",18],["Aluminium_Pellet",9],["Windows",2],["Tyres",10]],1,""],
		["f_t370","A3FL_T370","car",375,[["Steel_Pellet",19],["Aluminium_Pellet",9],["Windows",2],["Tyres",10]],1,""],
		["f_t440","A3FL_T440","car",375,[["Steel_Pellet",20],["Aluminium_Pellet",10],["Windows",2],["Tyres",10]],1,""],
		["f_t440_Gas_Tanker","A3FL_T440_Gas_Tanker","car",375,[["Steel_Pellet",20],["Aluminium_Pellet",10],["Windows",2],["Tyres",10]],1,""],
		["f_Drill_Trailer","A3PL_Drill_Trailer","car",900,[["Steel_Pellet",2],["Tyres",2]],1,""],
		["f_Small_boat_trailer","A3PL_Small_Boat_Trailer","car",900,[["Steel_Pellet",5],["Tyres",3]],1,""],
		["f_Car_Trailer","A3PL_Car_Trailer","car",900,[["Steel_Pellet",7],["Tyres",4]],1,""],
		["f_Tanker_Trailer","A3PL_Tanker_Trailer","car",350,[["Steel_Pellet",10],["Tyres",8]],1,""],
		["f_Box_Trailer","A3PL_Box_Trailer","car",350,[["Steel_Pellet",10],["Tyres",12]],1,""],
		["f_Lowloader","A3PL_Lowloader","car",350,[["Steel_Pellet",10],["Tyres",12]],1,""],
		["f_mailtruck","A3PL_MailTruck","car",350,[["Steel_Pellet",8],["Aluminium_Pellet",5],["Windows",2],["Tyres",4]],1,""],
		["f_Mini_Excavator","A3PL_MiniExcavator","car",425,[["Steel_Pellet",18],["Aluminium_Pellet",5],["Windows",2]],1,""],
		["f_C_Van_02_transport_F","C_Van_02_transport_F","car",375,[["Steel_Pellet",12],["Aluminium_Pellet",12],["Windows",4],["Tyres",4]],1,""]
	],

	["STR_Common_FactoryName_FactionVehicles",[3000.25,5352.92,0.4],
		["f_cvpi_FD","A3PL_CVPI_FD","car",350,[["Steel_Pellet",5],["Aluminium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_taurus_FD","A3FL_Taurus_FD","car",425,[["Steel_Pellet",9],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
        ["f_E350_A","EC_E350_A","car",425,[["Steel_Pellet",10],["Aluminium_Pellet",10],["Windows",2],["Tyres",6],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_f450","jonzie_ambulance","car",375,[["Steel_Pellet",10],["Aluminium_Pellet",13],["Windows",2],["Tyres",6],["blueprint_fifr",1]],1,"Reserved to FIFR"],
        ["f_F450_Brush","EC_F450_Brush","car",375,[["Steel_Pellet",17],["Aluminium_Pellet",13],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
        ["f_Explorer19_FD","EC_Explorer19_FD","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",14],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_F150_FD","A3FL_F150_FD","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
        ["f_F150_A","EC_F150_A","car",450,[["Steel_Pellet",25],["Aluminium_Pellet",16],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_Explorer_FD","A3FL_Explorer_Platinum_FD_20","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_tahoe_FD","A3PL_Tahoe_FD","car",425,[["Steel_Pellet",11],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_Silverado_FD","A3PL_Silverado_FD","car",375,[["Steel_Pellet",16],["Aluminium_Pellet",12],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_Silverado_FD_Brush","A3PL_Silverado_FD_Brush","car",375,[["Steel_Pellet",16],["Aluminium_Pellet",13],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_tahoe18_FD","A3FL_Tahoe_FD","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",13],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_Charger_Hellcat_20_FD","EC_Charger_Hellcat_20_FD","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_tanker","A3FL_T440_Water_Tanker","car",375,[["Steel_Pellet",20],["Aluminium_Pellet",10],["Windows",2],["Tyres",10],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_rescue","A3PL_Pierce_Rescue","car",375,[["Steel_Pellet",19],["Aluminium_Pellet",10],["Titanium_Pellet",1],["Windows",2],["Tyres",10],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_pumper","A3PL_Pierce_Pumper","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",10],["Titanium_Pellet",1],["Windows",2],["Tyres",6],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_hladder","A3PL_Pierce_Heavy_Ladder","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",11],["Titanium_Pellet",2],["Windows",2],["Tyres",10],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_DodgeRam_FD","EC_DodgeRam_FD","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fifr",1]],1,"Reserved to FIFR"],
		["f_cvpi_PDST","A3PL_CVPI_PD_Slicktop","car",350,[["Steel_Pellet",4],["Aluminium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_cvpi_PD","A3PL_CVPI_PD","car",350,[["Steel_Pellet",5],["Aluminium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_taurus_PD_ST","A3FL_Taurus_PD_ST","car",425,[["Steel_Pellet",8],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_taurus_PD","A3FL_Taurus_PD","car",425,[["Steel_Pellet",9],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
        ["f_E350_PD","A3FL_E350_PD","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",12],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_E350_PD_P","A3FL_E350_PD_P","car",450,[["Steel_Pellet",23],["Aluminium_Pellet",12],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
        ["f_Explorer19_PD_ST","EC_Explorer19_PD_ST","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",14],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Explorer19_PD","EC_Explorer19_PD","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",14],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_F150_PD_ST","A3FL_F150_PD_ST","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_F150_PD","A3FL_F150_PD","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_DodgeRam_PD_ST","EC_DodgeRam_PD_ST","car",450,[["Steel_Pellet",19],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_DodgeRam_PD","EC_DodgeRam_PD","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Explorer_PD_ST","A3FL_Explorer_Platinum_PD_Slicktop_20","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Explorer_PD","A3FL_Explorer_Platinum_PD_20","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_mustang_PDST","A3PL_Mustang_PD_Slicktop","car",470,[["Steel_Pellet",21],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Mustang_PD","A3PL_Mustang_PD","car",470,[["Steel_Pellet",22],["Aluminium_Pellet",12],["Titanium_Pellet",5],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_mustang15_PDST","A3FL_Mustang15_PD_ST","car",470,[["Steel_Pellet",16],["Aluminium_Pellet",20],["Titanium_Pellet",5],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Mustang15_PD","A3FL_Mustang15_PD","car",470,[["Steel_Pellet",17],["Aluminium_Pellet",20],["Titanium_Pellet",5],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_tahoe_PDST","A3PL_Tahoe_PD_Slicktop","car",425,[["Steel_Pellet",10],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_tahoe_PD","A3PL_Tahoe_PD","car",425,[["Steel_Pellet",11],["Aluminium_Pellet",7],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Silverado_PD_ST","A3PL_Silverado_PD_ST","car",375,[["Aluminium_Pellet",15],["Steel_Pellet",12],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Silverado_PD","A3PL_Silverado_PD","car",375,[["Aluminium_Pellet",16],["Steel_Pellet",12],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_tahoe18_ST","A3FL_Tahoe_PD_ST","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",13],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_tahoe18_PD","A3FL_Tahoe_PD","car",470,[["Steel_Pellet",22],["Aluminium_Pellet",13],["Titanium_Pellet",2],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_CamaroZL1_PD_ST","A3FL_CamaroZL1_PD_ST","car",470,[["Steel_Pellet",16],["Aluminium_Pellet",20],["Titanium_Pellet",7],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_CamaroZL1_PD","A3FL_CamaroZL1_PD","car",470,[["Steel_Pellet",17],["Aluminium_Pellet",20],["Titanium_Pellet",7],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_charger_PDST","A3PL_Charger_PD_Slicktop","car",375,[["Steel_Pellet",19],["Aluminium_Pellet",12],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_charger_PD","A3PL_Charger_PD","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Charger_Hellcat_20_PD_ST","EC_Charger_Hellcat_20_PD_ST","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
		["f_Charger_Hellcat_20_PD","EC_Charger_Hellcat_20_PD","car",450,[["Steel_Pellet",22],["Aluminium_Pellet",13],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
        ["f_Challenger_Hellcat_PDST","A3PL_Challenger_Hellcat_PD_ST","car",450,[["Steel_Pellet",21],["Aluminium_Pellet",14],["Titanium_Pellet",2],["Windows",2],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"],
        ["f_Escalade_PD_ST","A3FL_Escalade_PD_ST","car",450,[["Steel_Pellet",20],["Aluminium_Pellet",12],["Titanium_Pellet",1],["Windows",4],["Tyres",4],["blueprint_fisd",1]],1,""],
		["f_Bearcat","EC_Bearcat","car",1000,[["Steel_Pellet",60],["Aluminium_Pellet",20],["Titanium_Pellet",40],["Windows",5],["Tyres",4],["blueprint_fisd",1]],1,"Reserved to FISD"]
	],

	["STR_Common_FactoryName_IllegalClothings",[7651.51,8538.04,1.5],
		["f_A3PL_Indelicato_Family_Uniform","A3PL_Indelicato_Family_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Veloucci_Family_Man","A3PL_Veloucci_Family_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Sinaloa_Uniform","A3PL_Sinaloa_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_A3PL_Sinaloa_Vest","A3PL_Sinaloa_Vest","vest",5,[["Polyester",1]],1,""],
		["f_A3PL_Teiko_Rig_Lite","A3PL_Teiko_Rig_Lite","vest",5,[["Polyester",1],["blueprint_carrier_rig",1]],1,""],
		["f_A3PL_Teiko_Vest","A3PL_Teiko_Vest","vest",5,[["Polyester",1]],1,""],
		["f_Dep_Uniform_Man","A3PL_Dep_Uniform_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_High_Society_Uniform","A3PL_High_Society_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Kings_Services","A3PL_Kings_Services_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_The_Kings_Uniform","A3PL_The_Kings_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_The_Kings_Cap","A3PL_The_Kings_Cap","headgear",5,[["Polyester",1]],1,""],
		["f_Boyd_Combat_Uniform","A3PL_Boyd_Combat_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_StonedCombat_Uniform","A3PL_StonedCombat_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Deadwood_Fatigues_Uniform","A3PL_Deadwood_Fatigues_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Deadwood_Member_Vest","A3PL_Deadwood_Member_Vest","vest",5,[["Polyester",1]],1,""],
		["f_Deadwood_Prospect_Vest","A3PL_Deadwood_Prospect_Vest","vest",5,[["Polyester",1]],1,""],
		["f_Axel_Polo_Uniform","A3PL_Axel_Polo_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Axel_Cap","A3PL_Axel_Cap","headgear",5,[["Polyester",1]],1,""],
		["f_DepChief_Uniform","A3PL_DepChief_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DepCommand_Uniform","A3PL_DepCommand_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DepSenior_Uniform","A3PL_DepSenior_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DepSoldier_Uniform","A3PL_DepSoldier_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DepUniform_Uniform","A3PL_DepUniform_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DepUniform2_Uniform","A3PL_DepUniform2_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Depcap_Cap","A3PL_Depcap_Cap","headgear",5,[["Polyester",1]],1,""],
		["f_Cortez_Combat_Uniform","A3PL_Cortez_Combat_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_CortezSwimmer_Uniform","A3PL_CortezSwimmer_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Oathkeepers_Uniform","A3PL_Oathkeepers_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Oathkeepers_Swimmers","A3PL_Oathkeeper_Survival_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_A3PL_Oathkeepers","A3PL_Oathkeepers","vest",5,[["Polyester",1]],1,""],
		["f_DeathAngel_Fatigues1_Uniform","A3PL_DeathAngel_Fatigues1_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DeathAngel_Fatigues2_Uniform","A3PL_DeathAngel_Fatigues2_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DeathAngel_P_Uniform","A3PL_DeathAngel_P_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DeathAngel_VP_Uniform","A3PL_DeathAngel_VP_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DeathAngel_Sgt_Uniform","A3PL_DeathAngel_Sgt_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_DeathAngel_P_Vest","A3PL_DeathAngel_P_Vest","vest",5,[["Polyester",1]],1,""],
		["f_DeathAngel_VP_Vest","A3PL_DeathAngel_VP_Vest","vest",5,[["Polyester",1]],1,""],
		["f_DeathAngel_SGT_Vest","A3PL_DeathAngel_SGT_Vest","vest",5,[["Polyester",1]],1,""],
		["f_Southside_Uniform","A3PL_Southside_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Southside_Swimmers_Uniform","A3PL_Southside_Swimmers_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Roaches_Uniform","A3PL_Roaches_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Roaches_Vest","A3PL_Roaches_Vest","vest",5,[["Polyester",1]],1,""],
		["f_Boogaloo_Polo_Uniform","A3PL_Boogaloo_Polo_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Boogaloo_Swimmer_Uniform","A3PL_Boogaloo_Swimmer_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Boogaloo_Winter_Swimmer_Uniform","A3PL_Boogaloo_Winter_Swimmer_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Duvall_Swimmer_Uniform","A3PL_Duvall_Swimmer_Uniform","uniform",5,[["Polyester",1]],1,""],
		["f_Cortez_Boonie_Hat","A3LL_Cortez_Boonie","headgear",5,[["Polyester",1]],1,""]
	]
];
publicVariable "Config_Factories";

// If Craft xhave blueprint, ["Chance to fail", "% Items given back if fail"]
Config_Factories_BP = [100, 20]; 
publicVariable "Config_Factories_BP";